### PR TITLE
feat(module: tree): Add `SimplifySearchResults` to hide the nodes without any matched parent or child from the search results

### PR DESCRIPTION
**Pull request by huangjia2107**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   add `SimplifySearchResults` to hide the nodes without any matched parent or child from the search results  |
| 🇨🇳 Chinese |   添加 `SimplifySearchResults` 来简化搜索结果的显示，隐藏父节点或子节点均无匹配的节点   |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @huangjia2107 , please fix the encoding.

**Comment by huangjia2107** [comment]
@ElderJames all utf-8 with bom ?

**Comment by huangjia2107** [comment]
> Thanks for contribution @huangjia2107 , please fix the encoding.

@ElderJames fixed in the latest commit

**Comment by huangjia2107** [comment]
I will repull this request.

**Pull request closed without merging**
