### PR TITLE
fix(module:datepicker): Date picker panel click closing + some issues from #1431

### LINKED ISSUE #1431: DatePicker: The overlay panel closes when click any place
### Describe the bug

After update to 0.8.1-nightly-2104280412, the DatePicker overlay panel closes when click any place. If we want to use the header buttons, this causes troubles. 
image

### Further technical details
- AntDesign Nuget Package version: 0.8.1-nightly-2104280412

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
1. Fixes #1431 
2. Addresses parts of #1429 ([this comment](https://github.com/ant-design-blazor/ant-design-blazor/issues/1429#issuecomment-828196477)):
   a. When first clicked, the RangePicker panel will first display on the left side of the page.
   b. The height of the RangePicker is refreshed twice when it is opened.
3. When panel was opening, `OnBlur` event is being fired.
4. When Tab+Shift on `RangePicker` was leaving the input, it is not loosing focus.
5. Initial render of `RangePicker` if rendered above the input is placed too low when panel renedered above input element:
image
Closing and reopening the panel would fix that to expected behavior:
image

### 💡 Background and solution
1. `DatePicker` in `OnBlur` event handler was calling `Close()` method and should not.
2. a. This was an issue with `Overlay` manifesting only in server-side. I guess it wasn't manifesting anywhere else except `RangePicker` because of how complex the `RangePicker` is. Anyway, the issue there was that the `RangePicker` was starting with style set to `display: inline-flex` and then its position was calculated and adjusted to match input element. I changed that initial style to `display: inline-flex; visibility: hidden;` - we still need this to render and take space but not to be visible. 
2. b. It wasn't really refreshing height 2 times. The problem was that when panel should hide, it receives class `ant-slide-up-leave-active`. That class stays there. So when it is shown again, it is made first visible with that class, and then it gets proper `ant-slide-up-enter-active`. So basically on any consecutive open the picker was first being animated with leave and then with enter css class. My solution is to reset the class to enter class after it is closed.
3. Removed `Close()` method call.
4. Missing `AutoFocus = false` was added.
5. `RangePicker` was supposed to get `OverlayClassName="ant-picker-dropdown-range`. Otherwise first render was placing the pointing arrow incorrectly. It was only affecting the panel if it was rendered above the input.

Feature: added support for `Escape` button - matches the behaviour of react antD.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by anddrzejb** [comment]
@Zonciu Could you review my commit 934acca? I was trying to push it as a new PR but for some reason cherry-pick was still picking up commit from this PR...

Commit fixes [this part](https://github.com/ant-design-blazor/ant-design-blazor/issues/1429#issuecomment-828208070) of #1429.

What I found was that `DatePickerPanelBase.Value` that was not nullable. If `Value` passed from `DatePickerBase` was null, then `DateTime.Now` was assumed. Changed it, so value in `DatePickerPanelBase` is a nullable.

**Comment by Zonciu** [comment]
Sorry I'm too busy recently.

**Comment by anddrzejb** [comment]
Commit 7ad46ed addresses issues associated with week mode:
> 1. Week picker - week count for beginning of the year is showing incorrectly. For example first week in 2020 is actually starting from the second
>    image
>    and it should show like this:
>    image

**Comment by mutouzdl** [comment]
@anddrzejb 
I looked it over and found nothing wrong.

By the way, I found a problem, but this problem exists in the current version(0.8.0).
RangePicker(date mode with timer) cannot select the correct end date, nor can you select months forward.
Steps:
1. Choose a start date
2. Select an end date, and you will find that the end date is always one month longer than the selected date, and you cannot switch to the previous month

-----------translate-----------
我检测了一遍，没有问题。

顺便提一下，我发现一个问题，但这个问题在当前版本(0.8.0)中就存在了。
RangePicker（带时间的日期模式）不能选择正确的结束日期，也无法向前选择月份。

步骤：
1. 选择一个开始日期
2. 选择一个结束日期，此时会发现，结束日期会永远比选择的日期多1个月，并且无法切换到上一个月份

issue

**Review by mutouzdl — APPROVED** [review]

**Comment by anddrzejb** [comment]
@mutouzdl Thanks. Regarding the issue - I will add it to aggregated issue list #1429 we created with @Zonciu . I noticed there are several issues with `RangePicker` with timer, so this adds another one...

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
