### PR TITLE
test: new TestKit csproj for public tests

### PR DESCRIPTION
**Pull request by MutatePat**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?) - New csproj

### 🔗 Related issue link

Discussed in #1233 

### 💡 Background and solution

This new folder structure and csproj will allow other applications to test AntDesign-based apps.  

### 📝 Changelog

Internal Tests: New folder structure required to distinguish between the TestKit and the tests.
TestKit: new nuget package for enabling tests in public projects.

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |   x        |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MutatePat** [comment]
@ElderJames Not sure if the project is setup correctly, but what do you think?

**Comment by ElderJames** [comment]
Please switch the target branch to `feature`.

**Comment by MutatePat** [comment]
Changed the target

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1248) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1248) before we can accept your contribution.<br/><br/>:x: MutatePat [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1248)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1248) it.</sub>

**Comment by ElderJames** [comment]
@MutatePat Please sign the CLA.

**Comment by MutatePat** [comment]
> @MutatePat Please sign the CLA.

Signed

**Review by ElderJames — APPROVED** [review]

**Comment by MutatePat** [comment]
I believe all that needs to be done now is to create the new NuGet package, and then I can create the TestContext and the tests( in the main test project, not testkit)

**Comment by ElderJames** [comment]
Alright, I will continue to update the ci script to do that.

**Pull request merged**
