### PR TITLE
feat(Alert): added alert loop component

### PR DESCRIPTION
**Pull request by MutatePat**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

Issues: #501
Milestones: 0.8.0 - MILESTONE: March 2021
 
### 💡 Background and solution

Allows user to display a list of messages on a loop in an Alert component.

alertloop
(Component has been renamed to AlertLoop in this PR, not LoopTest!)

### 📝 Changelog

💡 Alert: Show looping messages object in alert box

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     x      |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by MutatePat** [comment]
need to update docs/demo, but first can a reviewer tell me if the code is okay? I worry about copying the Alert API, but I didn't want to touch the original Alert component, please check! Will discuss more on Discord.

**Comment by ElderJames** [comment]
Awesome! I think it's better to create a component names `LoopText` for the looping text, and then put it in the Alert.

**Comment by MutatePat** [comment]
> Awesome! I think it's better to create a component names `LoopText` for the looping text, and then put it in the Alert.

Will do :), btw is the target branch correct?

**Comment by ElderJames** [comment]
The branch should switch to `feature`. And the new component may should name `TextLoop`  like react impl.

**Comment by MutatePat** [comment]
The same error from my PC is showing here, 
```The command "dotnet site/AntDesign.Docs.Build.CLI/bin/Debug/net5/AntDesign.Docs.Build.CLI.dll demo2json /home/runner/work/ant-design-blazor/ant-design-blazor//site/AntDesign.Docs/Demos /home/runner/work/ant-design-blazor/ant-design-blazor//site/AntDesign.Docs/wwwroot/meta" exited with code 255.```
@ElderJames could you assist?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1250) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1250) before we can accept your contribution.<br/><br/>:x: MutatePat [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1250)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1250) it.</sub>

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
