### PR TITLE
Fix issue #1634 - Modal dialogs not showing anymore

### PR DESCRIPTION
**Pull request by rzvdaniel**
### 🤔 This is a
- [x] Bug fix

### 🔗 Related issue link

This is an issue I've opened myself just before the pull request:
https://github.com/ant-design-blazor/ant-design-blazor/issues/1634

### 💡 Background and solution

**1. Describe the problem and the scenario.**
Modal dialogs don't open anymore because of refactoring done for Button in d9fec3ce54905db8f2777b829aebb99738f7c914.

**2. GIF or snapshot should be provided if includes UI/interactive modification.**
Not needed

**3. How to fix the problem, and list final API implementation and usage sample if that is an new feature.**
To fix the issue, I'm removing the unnecessary Search parameter left in Modal dialogs.

### 📝 Changelog

No breaking changes.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is not needed
- [x] Demo is not needed
- [x] Changelog not needed

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1635) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1635) before we can accept your contribution.<br/><br/>:x: rzvdaniel [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1635)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1635) it.</sub>

**Comment by anddrzejb** [comment]
Great catch and quick fix! Thanks! It seems to me that property `Search` in class `ButtonProps` could also be removed. Or at least add `[Obsolete]` annotation, in order not to introduce a breaking change...

**Comment by rzvdaniel** [comment]
Hi, @anddrzejb !

No worries, it just happened to use the latest version of `master` and play with the modal yesterday.

Because the Search parameter was already removed from Button, maybe removing it also from `ButtonProps` makes more sense than annotating it as `[Obsolete]`?

Razvan

**Comment by anddrzejb** [comment]
It probably is. However if anyone is using it, it would introduce a breaking change. We are still in preview, so I guess breaking changes are expected. Unless @ElderJames has a different point of view.

**Comment by ElderJames** [comment]
Thanks for the contribution @rzvdaniel !
I agree with you, you can just delete the `Search` parameter from `ButtonProps`.

**Comment by ElderJames** [comment]
@anddrzejb This parameter appears to be a legacy bug and should not be used very often.

**Comment by rzvdaniel** [comment]
Hi, guys!

I've pushed one more commit to remove `ButtonProps.Search` property. This was a good idea because it revealed another use of `Button.Search` in Popconfirm.razor, and I removed it from there too.

Best!
Razvan

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
