### PR TITLE
fix:(module: datepicker): tab key does not confirm the value

### PR DESCRIPTION
**Pull request by Alexbits**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#2841

### 💡 Background and solution

This fixes two issues from #2841. 

Also, it brings RangePicker's behavior closer to the original antdesign. It gives the ability to select the range values more conveniently. Now it's possible to select the start date later than the end date without clearing the value.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Could we also support the short cut for date/month/year navigate?

**Comment by Alexbits** [comment]
> Could we also support the short cut for date/month/year navigate?

@ElderJames What shortcut do you mean?

**Comment by ElderJames** [comment]
@Alexbits Just use keyboard to choose date

**Review by ElderJames — APPROVED** [review]

**Comment by Alexbits** [comment]
> @Alexbits Just use keyboard to choose date

@ElderJames I will look into this later. The tab key should move the input focus to the datetimepanel, and this should allow selecting days with the keyboard.  I will look into this later.

**Comment by ElderJames** [comment]
@Alexbits That's great! Thank you.

**Comment by YingXiaoMing** [comment]
> this

how to use focus, it press tab can skip,the datepicker be empty

**Pull request merged**
