### PR TITLE
feat(module: select): Introduce SearchInput parameter for setting seach input manually

### PR DESCRIPTION
**Pull request by Velociraptor45**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

I need to manage the search input that's displayed in the Select outside the component, see #4231.

### 💡 Background and solution

This PR introduces the `SearchInput` parameter that lets the user set the search input from outside, which brings one big important note: If this parameter is set, we cannot manage this value on the inside anymore (e.g. clear it on selecting a value or on unfocus), but the user has to do it on their own. Otherwise, we'd get conflicting states inside the component and outside of it (you'll see this especially in the `SelectBase` when the `_searchValue` is only cleared if `_manageSearchInputExternally` is `false`).
However, I tried to keep the changes a non-invasive as possible.

I'm conflicted as to naming the parameter `SearchInput` or `SearchValue`. The latter would conform to the existing backing field, whereas the former is more user-friendly in my opinion. Let me know what you think.

I tried to write a test for ever test case there is, but maybe double-check if I forgot some.
I also did intensive manual testing with all three Select types (default, multiple, tags) to make sure this works.
There are no breaking changes.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Add SearchInput property that lets the user set & manage the search input outside the component |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Velociraptor45** [comment]
@dotnet-policy-service agree

**Comment by ElderJames** [comment]
Thanks for contribution @Velociraptor45 , what is the difference between SearchInput and SearchValue? I thought you wanted custom input controls.

**Comment by Velociraptor45** [comment]
Hey there, @ElderJames, thanks for taking a look at the PR.

The tricky thing here is that there are two components that manage their own input state.
- The `SelectContent` hosts the actual HTML input field and manages the value that's inside that input field (in `_inputString`)
- The `Select` gets a callback from `SelectContent` upon user input into the input field (after the debouncer is expired) and executes the search. However, it again keeps the state of the search value (`_searchValue`) inside its own component.

Previously, the only place where the user-invoked change of the input value could take place was the HTML input field (managed by `SelectContent`). Clearing the `_inputString` in `SelectContent` was triggered via an internally accessed `ClearSearch` method in `SelectBase` upon unfocus or item selection.
But now it's also possible that the input value comes from the `Select` component as that's the entrypoint for setting the `SearchInput`. Thus, we have to use the already existing propagation of `_searchValue` (from `Select`) into `SearchValue` (in `SelectContent`) and make sure this updates `_inputString`.

I tried to draw the relationship:
Select

Did that answer your question?

What I'm aiming at is a parameter that sets the value in the input field, no matter what happens inside the Select component. Just like the `Value` property, I want the `Select` to display exactly what I tell it to (via the new `SearchInput` parameter).

use_select

If the user types characters into the input field, the `OnSearch` callback in the `Select` is eventually triggered, and I can grab that and update the search input that I manage in my own code. This will achive the same behavior as today, using the `SearchInput`. However, it also enables me to alter the `SearchInput` from other places in my code even if there was no user input.

select_process

**Comment by ElderJames** [comment]
Ok, that's fine. The parameter name need to be changed to `SearchValue`, and the behavior should like the ant design react.


image

**Comment by Velociraptor45** [comment]
@ElderJames, I will do the name change, but could you elaborate on the "ant design react behavior" part? I'm not a react dev and can't check for myself real quick. What's the exact behavior of that parameter in your react solution? The documentation is not really verbose on that.

**Comment by ElderJames** [comment]
It would show the searchValue allways , only can't be changed by the inputbox that only can be changed by code.

image

**Comment by Velociraptor45** [comment]
@ElderJames Thanks for the clarification. With that requirement, I'll close the PR & issue as this would defeat the purpose of a search-select from my pov.

**Pull request closed without merging**
