### PR TITLE
feat: add page-header components

### PR DESCRIPTION
**Pull request by TimChen44**

### CODE REVIEW

**Comment by ElderJames** [comment]
Thank you for your contribution @TimChen44 !
It seems that this component is not fully implemented.

**Comment by TimChen44** [comment]
近期会逐步实现剩余的内容。提交防止发生与别人重复工作。
The remaining content will be gradually realized in the near future. Submit to prevent duplication of work with others.

**Comment by TimChen44** [comment]
遇到一些问题正在处理。提交是防止别人重复劳动。近期会实现剩余的内容。
Some problems are being dealt with. Submission is to prevent others from duplicating work. The remaining content will be realized in the near future.

**Comment by TimChen44** [comment]
功能基本完成。但是NavigationManager不存在Back()方法。如何实现返回上一页？
The function is basically completed. But there is no Back() method for NavigationManager. How to return to the previous page?

**Comment by Epictek** [comment]
> 功能基本完成。但是NavigationManager不存在Back()方法。如何实现返回上一页？
> The function is basically completed. But there is no Back() method for NavigationManager. How to return to the previous page?

Could use JSInterop to run `history.back()`

**Comment by TimChen44** [comment]
1、完成page-header的迁移
2、修正了statistic组件Value对string类型不支持的问题

**Pull request merged**
