### PR TITLE
i18n: remove comments from locale json files

### PR DESCRIPTION
**Pull request by ogix**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

After updating to v20.0.2 we started getting exception:
`JsonReaderException: '/' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 3 | BytePositionInLine: 4.`

After some investigation I have noticed that there is a problem reading `lt_LT` locale. Then I noticed that there are comments in lt locale json file and JSON deserialized does not expect them.

So this PR just removes comments that causes exception.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | remove comments from lt locale json file  |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @ogix , we make a mistake. Would you please help fix other locale files?

**Comment by ogix** [comment]
ok, I can check other files as well

**Comment by ogix** [comment]
updated

**Review by ElderJames — APPROVED** [review]
Thank you!

**Pull request merged**
