### PR TITLE
Add support for column names from Display attribute

### PR DESCRIPTION
**Pull request by Bintel**
Did we forget to modify this?

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1380) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1380) before we can accept your contribution.<br/><br/>:x: Bintel [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1380)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1380) it.</sub>

**Comment by Zonciu** [comment]
Duplicate https://github.com/ant-design-blazor/ant-design-blazor/pull/1372/commits/e095072095eaf0476b4d1090d155c9f6522d4e15

**Comment by Bintel** [comment]
@Zonciu Thanks for your confirm. But I really confused that I can't find this commit, why does it not work?

**Comment by Zonciu** [comment]
well……it's not yet merged, #1372

**Comment by Bintel** [comment]
Alright, hope it will merge soon.

**Pull request closed without merging**
