### PR TITLE
fix(module:table): locale fix

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Crashing exceptions whenever locale set to something else than zn-CH or en-US.

### 💡 Background and solution
Applied same solutions as in PR #1054 - added defaults (taken from en-US).
Included translations in en-GB & pl-PL for the missing fields. 

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by ElderJames — APPROVED** [review]
I will fix in next release.

**Comment by anddrzejb** [comment]
Mind that if you won't add it in current release, the table will not render at all (for other regional settings).

**Comment by ElderJames** [comment]
@Zonciu noticed me here was a workaround https://github.com/dotnet/runtime/issues/31433

**Comment by anddrzejb** [comment]
That is very cool. And should protect tbe components from future issues like this. But are you going to add it before v0.8 release?

**Pull request merged**
