### PR TITLE
fix(module: select): Fixed multiple issues

### PR DESCRIPTION
**Pull request by ElDiddi**
Hello everyone,

fix(module: select): Typo in method generation
fix(module: select): Fixed empty data image
fix(module: select): Fixed "focused"-style problem, now it looks like the React implementation
fix(module: select): Internal server error when the page was reloaded (#695)
fix(module: select): Fixed multiple reset issues (#674, #557)
fix(module: select): Added 'No Data' on `Select Mode="multiple"` when `HideSelected ` is `true` and all options are selected
fix(module: select): Added clear button to `Select Mode="multiple"` and `Select Mode="tags"` (#588)
fix(module: select): Default value for `OptionLabelProp` was not set. (Select.razor.cs - Line 275-277) (Makes the workaround with the multiple `@item's` obsolete)

docs(module: select): Added/Changed some demos for testing purposes (e.g. #698) 
style(module: select): Removed unused usings, fixed some code style issues

### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [x] Component style update
- [x] Code style optimization

### 🔗 Related issue link

1. #674  
2. #557
3. #695
4. #588

### 📝 Changelog
The reload of the page now works with the select modules. 

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated
- [x] Demo is updated
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElDiddi** [comment]
@ElderJames 
After I was a bit overwhelmed with my git client, I closed the previous PR and created a new one with only one commit.

**Comment by ElderJames** [comment]
Hi @ElDiddi ,thank you for contributions again.

It seems that the `ResetFormHandler` method in the show-in-form-modal demo doesn't work.

**Review by ElderJames — APPROVED** [review]

**Comment by ElDiddi** [comment]
Hey @ElderJames ,
this is correct (#515). I tried to override the `ResetValue` method of the base class `AntInputComponentBase<TValue>`. But this does not work because the class is not `virtual`. I think we have to take a closer look at how to solve this problem.

Kind regards

**Comment by ElderJames** [comment]
Just feel free to make the method virtual.

**Pull request merged**
