### PR TITLE
fix(module:select) MaxTagCount behaves properly for non-responsive scenarios

### LINKED ISSUE #1746: MaxTagCount in Select on 'multiple' mode
There is a problem with using `MaxTagCount` property in Select component with mode `multiple`. When I use it, class `ant-select-selection-overflow-item` has 0px value in `height` what cause that none items in select are visible. Also `opacity` is incorrect for me, it is chaning on 0.2. 

I sent screen below:
AntBlazor_Bug

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Fixes #1746

### 💡 Background and solution
Fixed the bug. Added XML comments.
Fixed order in english docs.
Redid Chineese docs (missing translations).
Added test scenario for MaxTagCount when non-responsive

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Hi @anddrzejb ,welcome back.

I am preparing to release 0.9, does this need to be merged in?

**Comment by anddrzejb** [comment]
@ElderJames if you want the fix to be in 0.9, then probably yes. But I see there are some issues that weren't there before. Probably came from merging with feature. I may not be able to fix it right away.

**Comment by ElderJames** [comment]
Ok, so let's release it in 0.9.1 this weekend.

**Comment by anddrzejb** [comment]
As you wish. I actually did manage to merge the changes in `Select` component coming from feature branch, but I am not in a hurry. The OP of #1746 may be in a hurry, but I do not know that 🤷🏻‍♂️ .

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
