### PR TITLE
fix(module: tabs): stops tabs buttons from flickering when icons are …

### PR DESCRIPTION
**Pull request by diegofrata**
### 🤔 This is a ...

- [X] Bug fix
- [X] Site / documentation update

### 🔗 Related issue link

Flicker issue: not raised.
Documentation issue: https://github.com/ant-design-blazor/ant-design-blazor/issues/619

### 💡 Background and solution

When changing switching between tabs, the tab bar will flicker if there are any icons present. This flicker also causes the tab ink to be calculated incorrectly as the icon width is not accounted for. This PR fixes the flicker and mitigates the ink offset and width calculation issue.

This PR fixes the flickering issue by adding @key to the tab nav list, which avoids re-rendering all tab buttons anytime a tab switch occurs.

Also, this PR fixes a problem with documentation referenced on issue #619.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Hello @diegofrata ,glad you've come.

I've just thought about redesigning the tabs and making `TabPane` a separate component.
I've done some work on `refactor/tabs` branch. Could you help to finish it?

**Comment by diegofrata** [comment]
@ElderJames yes I can, but for now, can we merge this in? I have my own needs for this fix. :)

**Comment by ElderJames** [comment]
That's fine.

**Review by ElderJames — APPROVED** [review]

**Comment by diegofrata** [comment]
@ElderJames I don't have rights to merge this. Would you mind merging this in?

**Comment by ElderJames** [comment]
@diegofrata Thank you

**Pull request merged**
