### PR TITLE
feat(module: cascader): display indicator when options is null or empty

### PR DESCRIPTION
**Pull request by noctis0430**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
I also found the clear button an issue.  You can fix it in this PR, or you can open another one.  
cascader-clear-button

**Comment by noctis0430** [comment]
> I also found the clear button an issue. You can fix it in this PR, or you can open another one. cascader-clear-button

Ok. Will try to fix it in this PR.

**Comment by noctis0430** [comment]
> I also found the clear button an issue. You can fix it in this PR, or you can open another one. 

Just found out the clear button issue is a separated issue. Maybe we should close this and open another one for it. @ElderJames what do you think?

**Comment by noctis0430** [comment]
I also just found out that there's an existing default image to indicate empty options.

<p align = "left"></p>
<p align = "left">Default image</p>

<p align = "left"></p>
<p align = "left">Image in <code>&lt;Empty/&gt;</code> introduced in this PR</p>

For the sake of consistency, we should pick and use only one. Which should we choose?

**Comment by ElderJames** [comment]
This one.

**Review by mo3in — APPROVED** [review]

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
