### PR TITLE
feet-bug(module: Transfer): refresh data on change SelectedKeys or TargetKeys parameters

### PR DESCRIPTION
**Pull request by Magehernan**
I added reinitializacion of values when TargetKeys or SelectedKeys change from outside so it properly display the correct values.
I am using this in production and works fine, and is more easy to use this way. I hope it helps.

### 🤔 This is a ...

- [X] New feature
- [X] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @Magehernan ! 

I think it would be better to refrsh data in the setter of these parameters.

**Comment by ElderJames** [comment]
We also need to implement two-way binding, which is to update the external `SelectedKeys` and `TargetKeys` from within the component. Are you interested in helping?

**Comment by Magehernan** [comment]
> I think it would be better to refrsh data in the setter of these parameters.
I try but the problem is it need all the other parameter set for it to work, so for it to work it needed a flag for set initialized and then OnInitialized call Refresh... When i do this, it call Refresh 2 times and with this implementation only is called 1 so more efficient. Let me know what you think.

> We also need to implement two-way binding, which is to update the external `SelectedKeys` and `TargetKeys` from within the component. Are you interested in helping?

i can try, let me know if you prefer all on this pull request or the two-binding in another.

**Comment by ElderJames** [comment]
We can fix the two-way binding in another PR. In this PR we need to check if it fix https://github.com/ant-design-blazor/ant-design-blazor/issues/1229

**Comment by Magehernan** [comment]
I almost sure that it will be fix because i am doing async request to the server for fill the targetKeys and i was having that problem that the targetkeys don't appear and with this fix, it works fine, but maybe there is another case.

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
