### PR TITLE
feat: add algolia search

### PR DESCRIPTION
**Pull request by Epictek**
Since both React Ant Design and Angular Ant Design use algolia search I thought it would be fitting to also use it.

Currently using my own API key so would need to change it to your own and self host the scraper (github action?)
or join their program at https://docsearch.algolia.com/apply/

Config I used to index the search based on [ant designs config](https://github.com/algolia/docsearch-configs/blob/master/configs/ant_design.json):
```json
{
  "index_name": "ant_design_blazor",
  "start_urls": [
    {
      "url": "https://ant-design-blazor.github.io/zh-CN/",
      "tags": [
        "cn"
      ]
    },
    {
      "url": "https://ant-design-blazor.github.io/en-US/",
      "tags": [
        "en"
      ]
    }
  ],
  "stop_urls": [
    "/changelog"
  ],
  "selectors": {
    "lvl0": {
      "selector": ".ant-menu-submenu-selected h4",
      "global": true,
      "default_value": "Documentation"
    },
    "lvl1": "article h1",
    "lvl2": "article h2",
    "lvl3": "article h3",
    "lvl4": "article h4",
    "lvl5": "article h5",
    "text": "article p, article li"
  },
  "strip_chars": "#",
  "min_indexed_level": 1,
  "js_render": true,
  "js_wait": 5
}
```

Also fixed a bug when component url has # at the end it would cause it to crash e.g. https://ant-design-blazor.github.io/en-US/components/button#ant-blazor-3bdd02fe-76cf-4341-b376-d74205671d36

### CODE REVIEW

**Comment by ElderJames** [comment]
Thank you very much @Epictek !
I suggest using our [CLI project](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/site/AntDesign.Docs.Build.CLI) to generate metadata.

**Comment by Epictek** [comment]
>  I suggest using our [CLI project](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/site/AntDesign.Docs.Build.CLI) to generate metadata.

Not sure I follow, How do you suggest using the CLI project?
Would probably be much easier to just let algolia host the crawler https://docsearch.algolia.com/docs/who-can-apply

**Comment by ElderJames** [comment]
Oh, it would be nice to have an official crawler😊
But we need to think about networking and webassembly. We have two sites that need to be supported at the same time.

**Comment by Epictek** [comment]
Crawler is based on chromium so will handle webassembly A-Okay and will this will work on any host (github/gitee/localhost). Also got the preview working now after not realising I needed to edit a different index.html

**Comment by ElderJames** [comment]
Excellent! I'll review it soon.

**Comment by ElderJames** [comment]
Are you finished? It looks different from ant design.

image

image

**Comment by Epictek** [comment]
Seems to be an issue with the scraping config, I'll look in to fixing it

**Comment by ElderJames** [comment]
It looks good. Is it finished yet?

**Comment by Epictek** [comment]
All the work on my end is finished (unless you find any faults). Just need you to contact algolia to get signed up for the docsearch program, might take up to a week for them according to some staff on discord due to the amount of requests they get.

**Comment by ElderJames** [comment]
Thank you @Epictek !
Ok, I have applied for it, and I will modify this PR when I get a reply, and then merge it.

**Comment by ElderJames** [comment]
Hi, algolia reject my applying, could you help us to get one?

**Comment by Epictek** [comment]
what did they say?

**Comment by ElderJames** [comment]
They ask us to ensure our site must only relay on server side.
But I find that I can use the free plan, I will try it tomorrow.

**Comment by Epictek** [comment]
That's intresting as I believe ant design docs are hosted on github as well

**Comment by ElderJames** [comment]
I can't modify this PR, so I merge first and submit another PR.

**Pull request merged**
