### PR TITLE
In the case of dynamic loading columns, System.IndexOutOfRangeException exception may occur here.

### PR DESCRIPTION
**Pull request by codeox-he**
In the case of dynamic loading columns, System.IndexOutOfRangeException exception may occur here.
But I am not familiar with the overall code and can only simply grow the ColIndexOccupied array.
Please help for improve it.

### 🤔 This is a ...

- [ ] New feature
- [*] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @codeox-he , could you please provide a reproduce sample to explain the issue and we could debug with it.

**Comment by codeox-he** [comment]
> Thanks for contribution @codeox-he , could you please provide a reproduce sample to explain the issue and we could debug with it.
Okay, I'll try to reproduce this situation.

**Comment by ElderJames** [comment]
@codeox-he Please sign the CLA.

**Comment by ElderJames** [comment]
I have fixed the issue. Thank you!

**Pull request closed without merging**
