### PR TITLE
Allow to disable RebuildColumns in table

### PR DESCRIPTION
**Pull request by agolub-s**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by agolub-s** [comment]
We have a bug with changes from https://github.com/ant-design-blazor/ant-design-blazor/commit/ffa54d8ec247cff12ea4be5353b7d6ba60af48c8

i tryed to fix it without hack, but can't to do it without remove this logic. 
Table working without it, but i don't know, maybe this need for other cases

**Comment by ElderJames** [comment]
Could you reproduce the issue? May be this is not the real wrong way.

**Comment by agolub-s** [comment]
@ElderJames I did it, you can check. This will work if disable rebuilding Columns

**Comment by agolub-s** [comment]
@ElderJames Do you have any ideas how to fix this?

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
