### PR TITLE
refactor: Update TextArea.razor.cs

### LINKED ISSUE #3714: Can't Add Test for TextArea
I'm trying to write unit tests for a component that uses the TextArea component.  When I try to run my test, I get this error:
image
I can't add `Setup<TextAreaInfo>("AntDesign.interop.inputHelper.getTextAreaInfo", _ => true)` because `TextAreaInfo` is an internal class and not publicly accessible.  Can this be updated to be a public class or perhaps this added to the AntDesignTestBase?

### PR DESCRIPTION
**Pull request by bgraham123**
Updated TextAreaInfo to be a public class so that JSInterop calls can be setup for unit tests.

Closes #3714

### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @bgraham123 ，can't changing AntDesignTestBase solve this problem? I don't really want to change the access level here.

**Comment by bgraham123** [comment]
@ElderJames I can't add the JSInterop setup call to AntDesignTestBase because of the class being internal - its the same problem I have trying to add the set up call to my personal code base

**Comment by bgraham123** [comment]
@ElderJames bump on this please!

**Comment by ElderJames** [comment]
Ok, I think it can be divided into a separate class, and use the namespace  with `AntDesign.Internal`.

**Comment by bgraham123** [comment]
@ElderJames Updated

**Review by ElderJames — APPROVED** [review]

**Comment by bgraham123** [comment]
@ElderJames I don't think I have permissions to merge this PR
image

**Comment by bgraham123** [comment]
didn't mean to click close PR

**Comment by bgraham123** [comment]
@ElderJames Any idea why the build failed/can we run it again?

**Pull request merged**
