### PR TITLE
chore: add .NET 6 target framework to all projects (preview)

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 💡 Background and solution
Hot Reload is still not working. 
@ElderJames please check my github workflow changes. I am not very experienced in that area. 

Also - docs for wasm hosted are not workin for me. I get this error in browser (before and after net 6 so this bug is not related to adding net 6):
```log
Error: Found malformed component comment at Blazor:{"prerenderId":"57a82258d2f94aba804e9ffe74e34dbf"}
    i https://localhost:5001/_framework/blazor.webassembly.js:1
    r https://localhost:5001/_framework/blazor.webassembly.js:1
    r https://localhost:5001/_framework/blazor.webassembly.js:1
    r https://localhost:5001/_framework/blazor.webassembly.js:1
    r https://localhost:5001/_framework/blazor.webassembly.js:1
    discoverComponents https://localhost:5001/_framework/blazor.webassembly.js:1
    discoverComponents https://localhost:5001/_framework/blazor.webassembly.js:1
    g https://localhost:5001/_framework/blazor.webassembly.js:1
    s https://localhost:5001/_framework/blazor.webassembly.js:1
    s https://localhost:5001/_framework/blazor.webassembly.js:1
    r https://localhost:5001/_framework/blazor.webassembly.js:1
    r https://localhost:5001/_framework/blazor.webassembly.js:1
    g https://localhost:5001/_framework/blazor.webassembly.js:1
    <anonymous> https://localhost:5001/_framework/blazor.webassembly.js:1
    n https://localhost:5001/_framework/blazor.webassembly.js:1
    <anonymous> https://localhost:5001/_framework/blazor.webassembly.js:1
    <anonymous> https://localhost:5001/_framework/blazor.webassembly.js:1
```
### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Net 6 preview added   |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by anddrzejb** [comment]
@ElderJames It seems preview has failed. It obviously is because I messed something up in github actions... I am afraid you will have to have a look at this yourself, because I really don't know what I am doing here. Possibly the previews won't run on net 6?

**Comment by ElderJames** [comment]
@anddrzejb I will take a look.

**Comment by Gabsch** [comment]
Any news here?
I would really like to use .net 6 with hot reload :)

**Comment by anddrzejb** [comment]
> Any news here?
> I would really like to use .net 6 with hot reload :)

Me too, but judging by the [latest reply](https://github.com/dotnet/aspnetcore/issues/32309#issuecomment-909370890) it ain't gonna happen in net6 😞.

**Comment by ElderJames** [comment]
@anddrzejb  We need to continue this PR.

**Comment by anddrzejb** [comment]
I will try to have a look at this. I am a bit more knowledgeable, so maybe I won't fail this time 😏 .

**Pull request closed without merging**
