### PR TITLE
Number input type

### PR DESCRIPTION
**Pull request by quirynen**
### 🤔 This is a 

- [X] New feature

### 💡 Background and solution

Add the possibility to specify the type of the input for inputNumber and setting it by default to number since it's an input provided for numbers.

### 📝 Changelog

Idk if this is a breaking change but people already using InputNumber will have the numeric pad popping up instead of the full keyboard, it can be changed by setting the Type parameter to ="text".

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1757) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1757) before we can accept your contribution.<br/><br/>:x: quirynen [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1757)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1757) it.</sub>

**Comment by anranruye** [comment]
Notice that some browsers have special apperance for <input type="number" />(here I mean up and down arrows), but ant-design use standone up and down arrow elements, which may cause a confilct.

**Comment by quirynen** [comment]
And I guess this is certainly why you did not implement it? :(

**Comment by ElderJames** [comment]
Thanks for contacting us @quirynen 

I got a exception in the preview size.

image

**Comment by quirynen** [comment]
I was too quick for this one, there is indeed an exception with type number... (https://stackoverflow.com/questions/33406169/failed-to-execute-setselectionrange-on-htmlinputelement-the-input-elements)

**Pull request closed without merging**
