### PR TITLE
Update index.en-US.md

### PR DESCRIPTION
**Pull request by heroboy**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1808) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1808) before we can accept your contribution.<br/><br/>:x: heroboy [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1808)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1808) it.</sub>

**Comment by ElderJames** [comment]
Thanks for this contribution @heroboy . 

But I don't think this pr makes any sense. Can you continue to help us improve the documentation?

**Comment by heroboy** [comment]
@ElderJames 
before:

### AutoComplete

| Property | Description | Type | Default |
| --- | --- | --- | --- | --- |
| Backfill | backfill selected item the input when using keyboard | bool | false |
| Options | Data source for autocomplete | AutocompleteDataSource | - |
| Disabled | Set disabled | bool | - |

after:

### AutoComplete

| Property | Description | Type | Default |
| --- | --- | --- | --- |
| Backfill | backfill selected item the input when using keyboard | bool | false |
| Options | Data source for autocomplete | AutocompleteDataSource | - |
| Disabled | Set disabled | bool | - |

**Review by ElderJames — APPROVED** [review]
Oh, I see it in the en-US document. Thank you!

**Pull request merged**
