### PR TITLE
(fix) Table ExpandableRow not working with ActionColumn #1284

### PR DESCRIPTION
**Pull request by Magehernan**
### 🤔 This is a fix for issue #1284 

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1285) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1285) before we can accept your contribution.<br/><br/>:x: Magehernan [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1285)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1285) it.</sub>

**Review by ElderJames — COMMENTED** [review]
Thanks for contribution! 
Please add the expand button for the tree-data mode as well.

**Comment by Magehernan** [comment]
@ElderJames Hi, i add this and found another bug when using selection column but not in the fist position, so if the selection column is present it add 1 to expandcolumn so if you put in the second column the selection it will be the same as the selection and the selection column don't have code to show the expand button.... so i and looking for the position of the selection to modify the expandcolumn to show this correctly.

I will send this fix to.

**Comment by Magehernan** [comment]
@ElderJames so i found that if you use a Selection Column in Tree or Expand mode... it was breaking.

I fix it adding 1 if the selection column is less or equal index that the column you want to have the expand button, but this work fine only when you have none or one Selection Column, if you have two selection Column, the value of _selection.ColIndex is the last and it will work weard.

I don't want to make a lot of changes on the code. I make it better but the problems is more deep than this.

i don't know what to do?  
do i create a issue about the more than one selection column? 
I think maybe the better solution to this is make on the Column a parameter that indicate if show or not the expand button.... or in the table put a string for the name of de column you want to put the expand button.
Maybe there are betters solution.

**Comment by ElderJames** [comment]
I think we need to limit the user to setup the selection in the first column.

**Comment by Magehernan** [comment]
I look to the table for react ant.design and i try to move the selection column and i think it is not posible...

So i think you are right.

**Comment by Magehernan** [comment]
@ElderJames How do you link this force to one selection on first column?
I think maybe add parameters to the table to configure what type of selection the user want and remove the Column Tag <Selection /> 
Or if the user use the Selection Tag, not use the position of it and force it to be first?

Do you want i make this changes?

**Comment by ElderJames** [comment]
Yes, sure, we would happy if you can help! 😀 I prefer the second option.

You can create another PR base on `feture` branch to do that.

**Review by ElderJames — APPROVED** [review]

**Comment by Magehernan** [comment]
@ElderJames Hi again... 
I am strugling with what is best for this.
Looking at the code, i am getting more aware of the amount of complexity and problems there are.

The table only have a ISelectionColumn but if you use all you want, it will work, not perfect but will work. So this is the first problem, how to show error on the blazor page telling the dev that it is not allowed to put more than one Selection Column?

If we remove the posibility for adding more than one Selection Column then the problem that we have now will disappear.

So I think the best soluction isn't to force to the first position of the selection column. If it throw an exception when the selection column is not null and it try to assign it. Then we limit the use of it to one... so only if someone put 2, will have this exception.

https://github.com/ant-design-blazor/ant-design-blazor/blob/5263a7119ff6bd5ff4f7043a2f383f93adfa2068/components/table/Selection.razor.cs#L33-L50

If i add this code when you see the table it will throw the exepction... I don't really like this way but i am not an expert on blazor so if it can be done with an error when try to build your code then it will be a lot better.

```csharp
        protected override void OnInitialized()
        {
            base.OnInitialized();

            if (Table == null)
            {
                return;
            }

            if (IsHeader)
            {
                if (Table.Selection is not null)
                {
                    throw new System.InvalidOperationException("Only one Selection column is allowed");
                }
                Table.Selection = this;
            }
            else if (IsBody)
            {
                Table?.Selection?.RowSelections.Add(this);
            }
        }
```

I think is necesary a lot of work to make it cleaner... i don't have a lot of time to do it... but i leave this observation...
The feature for Expand is always a new column that the other columns expect Selection are adding when the index are equals... 
The feature for Tree is a button inside a column, same as Expand the column check and add it or not.

I think i can be better to split the login for this two features, the expand button can be a column type.
The tree can be a parameter for the columns when you choose if it show or not.

Then you can have multiples expand and multiples tree(if someone really need something like this) and becase it need to be explisit in the code, the dev will have what them put in code.

**Pull request merged**
