### PR TITLE
fix(module:datepicker): validate manually entered date against format

### LINKED ISSUE #1354: The date component will have a data error if you enter the year, month and day manually
For example, the current date is 2021-01-01, I want to manually go to enter the year, when I manually delete the 1 of 2021, the cursor will automatically jump to the very end, then the year automatically changed to 0202, at this time to enter or manually select are very troublesome, it is difficult to select the correct date.

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Fixes #1354 

### 💡 Background and solution
Previous string analyzer for manually entered date was very crud and was working with really overarching assumptions (I am bashing myself, as I was the one to create it). Current analyzer is meant to be much more versatile. 

datePicker_manualEntryValidation

However...
It seems to me that generally current format handling is incorrect and I believe it should be altered. At this stage, regional settings of the client's browser are completely ignored. Unless `Format` parameter is set, the format is always `yyyy-MM-dd` (if time the also + `HH:mm:ss`), regardless of browser's regional settings. Have a look at [this line](https://github.com/ant-design-blazor/ant-design-blazor/blob/d21bc89f38616ade2da4e48dd56c863a03cbc3c4/components/date-picker/internal/DatePickerBase.cs#L540) (this is a link to code before this PR), and you will see it is hardcoded. Shouldn't the format be taken from `DatePickerLocale`? And if consumer wants to alter format for only particular `DatePicker`, then should revert to `Format` property. 
I know antD seems to ignore regional settings, but I think this is incorrect. 

Also, `FormatAnalyzer` introduced by this PR basically handles standard date inputs - it does not (yet?) handles `Week` and `Quarter` input types. It could be probably(?) done, but I'd like to first address the regional settings issue.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Zonciu** [comment]
I think this should not be updated to 0205 year until the year string has 4 number characters.
image

Check ant design react version:
image

**Comment by Zonciu** [comment]
I mean here:
image

The `date picker body` should not render a invalid date at this moment, until the input string matches the format.

And the day selected mark is missing, according to this test: https://github.com/ant-design-blazor/ant-design-blazor/pull/1389/files#diff-71952683b85054528af1c8883b3cb5ac5eef189b255d831371e6dc489a01bd7fR38

**Comment by anddrzejb** [comment]
I think we clearly differ in opinion here - this is the part I was considering a feature. But since you are the reviewer, I applied the requested changes in commit 9a5b3d5.

**Comment by anddrzejb** [comment]
@Zonciu Commit ed5ba0a & a845ff2 address the conversation we had on discord and the [issue](https://discord.com/channels/753358910341251182/753779434380853347/834049125464801302) you mentioned there.

I was trying to recreate your issue after my changes, and I couldn't. My current results:
1. AntBlazor docs (wasm) with switch to locale:
datePicker_stringValid_Chinese
2. AntBlazor docs (wasm) issue recreation:
datePicker_stringValidatorWasmDocs

3. My tests with different combinations of current culture, locale, `Format` and default:
datePicker_stringValidatorServer

Here's the code if you would like to test it:
```razor
@using System.Globalization
@using System.Text.Json;
@CultureInfo.CurrentCulture.Name /(ui) @CultureInfo.CurrentUICulture.Name<br />
<DatePicker TValue="DateTime?" ShowTime="@true" Placeholder="@("Current culture")"/>
<br />
<br />
<DatePicker TValue="DateTime?" ShowTime="@true" Format="yyyy/MM/dd" Placeholder="@("Format set")"/>
<br />
<br />
<DatePicker TValue="DateTime?" Picker="@DatePickerType.Date" Locale="@CN" CultureInfo="CiCn" 
            Placeholder="@("CultureInfo=CiCn")"/>
<br />
<br />
<DatePicker TValue="DateTime?" Picker="@DatePickerType.Date" Locale="@CN" Format="yyyy/MM/dd" 
            Placeholder="@("Locale=CN & Placeholder")"/>

@code
{
    CultureInfo CiCn = CultureInfo.GetCultureInfo("zh-CN");
    DatePickerLocale CN = new DatePickerLocale
    {
        FirstDayOfWeek = DayOfWeek.Sunday,
        Lang = new DateLocale
        {
            YearFormat = "yyyy年",
            MonthFormat = "M月",
            DateSelect = "选择日期",
            WeekSelect = "选择周",
            MonthSelect = "选择月份",
            YearSelect = "选择年份",
            QuarterSelect = "选择季度",
            Today = "今天",
            DateFormat = "yyyy MM dd"
        }
    };
}
```

On top of that, I also found another issue. If you use `Placeholder`, it will only be shown in the beginning, then it will revert to defaults in locale. This is of course solvable, but in locale we have for example `DateSelect` and `DatePlaceholder`, they both contain the same. I think they are duplicating here, correct? So we either pick `*Placeholder` or `*Select`... And here is the issue recreation:
datePicker_vanishingPlaceholder

**Comment by anddrzejb** [comment]
@Zonciu Commit dd21191 added handling of manual entry for week, month, quarter & year mode.

**Comment by anddrzejb** [comment]
@Zonciu Commit c889ca0 contains fixes for suffix in year. I also added handling prefix in a date, for formats like this `XXyyyyZ` will be handled properly as well.

**Comment by anddrzejb** [comment]
@Zonciu Commit 19834f2 addresses only resetting dates when in conflict. It does not address any visual issues.

**Comment by anddrzejb** [comment]
@Zonciu Due to the issue you found with date format, I was forced to switch completely to `FormatAnalyzer` when generating date. The problem was coming from `BindConverter` - it uses current culture info to convert string to date. If `Format` was set to something else than what was in `CultureInfo`, then anyway the `CultureInfo` was used. Thus the problem with format set to `dd/MM/yyyy`. It seem that when you set a value like `01/12/2012`, this is perfectly convertible using `CultureInfo`, and this is what `BindConverter` seem to do.

Also, would you mind switching to PR comments when you have something for me to look at/fix? Discord is cool and dandy, but I think it splits needlessly the feedback and progress into multiple sources.

**Comment by Zonciu** [comment]
> Also, would you mind switching to PR comments when you have something for me to look at/fix? Discord is cool and dandy, but I think it splits needlessly the feedback and progress into multiple sources.

Sure, here is some issues I found:
### 1.
In `Date Format` demo, when I edit the string directly, and click the input field, the panel will go back to January. But if I select the date in panel first, it works fine.



------------------------------

### 2. 
When I press enter key, it will resets the opposing date, but when I click mouse on blank area to close the picker, it doesn't reset the opposing date.

**Comment by anddrzejb** [comment]
@Zonciu commit 22aafb9 contains a major number of changes. The bugs you mentioned last time unfortunately required some substantial changes. To be honest I am not sure if the bugs you mentions should be a part of this PR, but decided to fix them anyway. 
Both bugs were tightly related to detecting focus/blur and caching previous values. This is turn is connecting to our conversations in discord, where we said:
image

Because this is so related to focus/blur, I decided to build more complete navigation functionality. That means `DatePicker` & `RangePicker` should properly react to keys:
- arrow down - opens the picker panel with no cursor reposition, 
- arrow up - closes the picker panel with no cursor reposition, 
- enter/tab  - saves/reverts value and moves to next input
- shift+tab  - saves/reverts value and moves to previous input
The arrow up/arrow down behaviour gets a bit counter-intuitive when overlay moves above the control. I am not sure if to change it or not...React does not support this at all.

**Comment by Zonciu** [comment]
Oh I totally forgot the discussion... Anyway now the date picker is good to go, nice job!

**Review by Zonciu — APPROVED** [review]

**Comment by anddrzejb** [comment]
@Zonciu just found another bug, new commit 916a840. This thing was really troublesome... Anyway, hope you will not find any bugs in this one either.

**Comment by Zonciu** [comment]
Unfortunately, I did find some bugs...
### 1.
```
<RangePicker TValue="DateTime?[]" ShowTime="@true" />
```
When I select the end date and click `Ok` button, the date panel will be closed, it should switch the input cursor to start date. If I press Enter key in the end date picker, it works fine.

-------------------
### 2.

When I set the end quarter, the same quarter of the start quarter is disabled, it should be enabled.

image

**Comment by anddrzejb** [comment]
These are both pre-existing bugs not really related to this PR. From what I can see they originate from the panels. I know about couple other bugs in there that I did not address in here, 
For instance, there is week counting bug. Or bug that allows to select disabled dates (I am not talking about entering using keyboard but with a mouse click). As we once stated in our discord discussion, I intend to create issue for these, once this one is merged (or dropped although I really hope it will not be dropped 😏 ).

**Comment by Zonciu** [comment]
OK, then we'll leave the rest of the bugs for the next PR.

**Review by Zonciu — APPROVED** [review]

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
