### PR TITLE
Fix List order after datasource change

### PR DESCRIPTION
**Pull request by miguelkmarques**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#3750 and #3021

### 💡 Background and solution
In my project we have faced this issue mentioned above, so i have investigated the root cause.
Due to how HashSet works internally on .NET, when an item is removed from a HashSet (using the Remove method), the space allocation maybe still be there, so when a new item is added (using the Add method), it is not guaranteded to be inserted at the end of the HashSet, so it will not follow the order from the Datasource sent to the Select component, causing the bug.

The solution is to call the Clear method on the HashSet SelectOptionItems after storing all the existing options in the Dictionary, and add everything from the new Datasource, and keep the select state of existing items.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by miguelkmarques** [comment]
@dotnet-policy-service agree

**Comment by ElderJames** [comment]
Thanks for contribution @miguelkmarques , could you please add tests for the changes?

**Comment by miguelkmarques** [comment]
> Thanks for contribution @miguelkmarques , could you please add tests for the changes?

Sure, I will add some tests

**Comment by miguelkmarques** [comment]
I figured out that the component Parameter IgnoreItemChanges must be always false for my solution to work when the datasource is changed. So i have two options.
1. Update my solution to only call the Clear method when IgnoreItemChanges equals false. So this issue will stil occur when IgnoreItemChanges equals true (which is the default value).
2. Remove the Parameter IgnoreItemChanges, but this will be a breaking change, since it's used for performance reasons.

I'll follow the first option to not submit any breaking changes.

**Comment by ElderJames** [comment]
I prefer the first option too. Thank you for figureing out that.

**Comment by miguelkmarques** [comment]
Hi @ElderJames, solution updated and tests added, please review.
Thank you!

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
