### PR TITLE
feat(modul: menu) - MenuItem Title

### PR DESCRIPTION
**Pull request by ElDiddi**
Hi there,

a little PR for the menu modul. 

What's new?
+ MenuItem - `[Property] Title` - Allows to set the Title directly as parameter and not only as ChildComponent.

Changes:
+ Menu - `[Property] Selectable` - Angluar implementation adapted.

EN-US Documentation updated.

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
-

### 💡 Background and solution
-

### 📝 Changelog
-

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Hi @ElDiddi , thank you for your active participation!

But I think `IgnoreSelectionAfterClick` isn't used very often, can we do that when it is only in the dropdown?

**Comment by ElDiddi** [comment]
Hello James,

that is a good question. 

I think that the option is also useful in a normal menu. For example if you open an external web page in a new tab from a menu item. In that case the menu item would be selected even though you are still on the old page.
However, it would make more sense if that property is set per menu item and not globally in the menu. I could quickly adjust that.

**Comment by ElderJames** [comment]
Yes, you are right. We can also take a look into angular's routerlink implement.

**Comment by ElDiddi** [comment]
> Yes, you are right. We can also take a look into angular's routerlink implement.

Hehe i can't read the React/Angular source code. Thats why i try to use Blazor :D

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
