### PR TITLE
Cleanup button docs

### PR DESCRIPTION
**Pull request by Hona**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thank you! We would also like to turn the type of `ButtonType` to enum.

**Comment by Hona** [comment]
> Thank you! We would also like to turn the type of `ButtonType` to enum.

We can do another PR when ButtonType is an enum. Right now keeping const strings seems useful?

**Comment by ElderJames** [comment]
Yes, we merge this first. And the enum changes is target to feature branch.

**Comment by Hona** [comment]
Right. I will slowly go through each component again, as an improvement of #1131

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
