### PR TITLE
feat(module: datepicker): Add DateTimeOffset, DateOnly, TimeOnly support

### PR DESCRIPTION
**Pull request by Alexbits**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
#1236 
#1589 

### 💡 Background and solution

Allows to use the DateTimeOffset in DatePicker/RangePicker.

### 📝 Changelog

Adds DateTimeOffset, DateOnly, and TimeOnly support to DatePicker, RangePicker, and TimePicker.

⚠️Breaking change: OnChange and OnPanelChange events are generic now to allow the use of the new types.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Hello @Alexbits , I have fix the conflicts but there still are a test case is failed. Could you please fix it?

**Comment by Alexbits** [comment]
> Hello @Alexbits , I have fix the conflicts but there still are a test case is failed. Could you please fix it?

@ElderJames The Mask feature broke the RangePicker keyed input. There are issues in multiple places. Some of the changes do look absurd to me.

**Comment by Alexbits** [comment]
Hey @ElderJames, I've fixed the unit test issues. Some merged changes still look weird to me 🤷🏻‍♂️. But I do not have time to delve into them at the moment.

**Comment by ElderJames** [comment]
Thank you @Alexbits , I will continue to review thoes changes. I'm sorry I may have interfered with your efforts with this component.

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
