### PR TITLE
Standardize arguments

### PR DESCRIPTION
**Pull request by pathartl**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [X] Site / documentation update
- [X] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [X] Refactoring
- [X] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design-blazor/ant-design-blazor/issues/4304

### 💡 Background and solution
Most of the parameters for components accept strings as acceptable values. This makes it more difficult to develop because Intellisense has no idea what values the parameter can be. This PR changes almost every parameter to accept enums. For parameters that can take other string values (tag color for example), `OneOf<Enum, string>` has been used.

### 📝 Changelog
|       Component       |      Parameter     | Old Type                        | New Type                                    |
|:---------------------:|:------------------:|---------------------------------|---------------------------------------------|
| Alert                 | Type               | string                          | AlertType                                   |
| Avatar                | Shape              | string                          | AvatarShape                                 |
| Avatar                | Size               | string                          | OneOf<AvatarSize, string>                   |
| Badge                 | Color              | string                          | OneOf<BadgeColor, string>                   |
| Badge                 | PresetColor        | PresetColor?                    | Removed                                     |
| Badge                 | Status             | string                          | BadgeStatus?                                |
| Button                | Type               | string                          | ButtonType?                                 |
| Button                | Size               | string                          | ButtonSize                                  |
| Button                | Shape              | string                          | ButtonShape                                 |
| Button                | FormSize           | string                          | FormSize                                    |
| ButtonGroup           | Size               | string                          | ButtonGroupSize                             |
| Calendar              | Mode               | string                          | CalendarMode                                |
| Card                  | Type               | string                          | CardType                                    |
| Card                  | Size               | string                          | CardSize                                    |
| Carousel              | DotPosition        | string                          | CarouselDotPosition                         |
| Carousel              | Effect             | string                          | CarouselEffect                              |
| Cascader              | Size               | string                          | InputSize                                   |
| Collapse              | ExpandIconPosition | string                          | CollapseExpandIconPosition                  |
| Comment               | Placement          | string                          | CommentPlacement                            |
| AntInputComponentBase | FormSize           | string                          | FormSize                                    |
| AntInputComponentbase | Size               | string                          | InputSize                                   |
| DatePickerInput       | Size               | string                          | InputSize                                   |
| Descriptions          | Layout             | string                          | DescriptionsLayout                          |
| Descriptions          | Size               | string                          | DescriptionsSize                            |
| Divider               | Type               | DirectionVHType                 | DividerType                                 |
| Divider               | Orientation        | string                          | DividerOrientation                          |
| Drawer                | Placement          | string                          | DrawerPlacement                             |
| DropdownButton        | Size               | string                          | ButtonSize                                  |
| DropdownButton        | Type               | OneOf<string, (string, string)> | OneOf<ButtonType, (ButtonType, ButtonType)> |
| Flex                  | Wrap               | string                          | OneOf<FlexWrap, string>                     |
| Flex                  | Justify            | string                          | OneOf<FlexJustify, string>                  |
| Flex                  | Align              | string                          | OneOf<FlexAlign, string>                    |
| Flex                  | Gap                | string                          | OneOf<FlexGap, string>                      |
| Form                  | Layout             | string                          | FormLayout                                  |
| Form                  | Size               | string                          | FormSize?                                   |
| Form                  | Method             | string                          | HttpMethod                                  |
| Row                   | Align              | string                          | RowAlign                                    |
| Row                   | Justify            | string                          | RowJustify                                  |
| Icon                  | Theme              | string                          | IconThemeType                               |
| Input                 | Type               | string                          | InputType                                   |
| InputGroup            | Size               | string                          | InputSize                                   |
| AntList               | Size               | string                          | ListSize                                    |
| Modal.ButtonProps     | Type               | string                          | ButtonType                                  |
| Modal.ButtonProps     | Shape              | string                          | ButtonShape                                 |
| Modal.ButtonProps     | Size               | string                          | ButtonSize                                  |
| Modal                 | OkType             | string                          | ButtonType                                  |
| Popconfirm            | OkType             | string                          | ButtonType                                  |
| Result                | Status             | string                          | ResultStatus                                |
| Skeleton              | AvatarSize         | OneOf<int?, string>             | OneOf<SkeletonElementSize, string>          |
| Skeleton              | AvatarShape        | string                          | SkeletonElementShape                        |
| SkeletonElement       | Type               | string                          | SkeletonElementType                         |
| SkeletonElement       | Size               | OneOf<int?, string>             | SkeletonElementSize                         |
| SkeletonElement       | Shape              | string                          | SkeletonElementShape                        |
| Space                 | Align              | string                          | OneOf<SpaceAlign, string>                   |
| Space                 | Direction          | DirectionVHType                 | SpaceDirection                              |
| Space                 | Size               | OneOf<string, (string, string)> | OneOf<SpaceSize, string, (string, string)>  |
| Spin                  | Size               | string                          | SpinSize                                    |
| Step                  | Status             | string                          | StepsStatus                                 |
| Steps                 | Direction          | string                          | StepsDirection                              |
| Steps                 | LabelPlacement     | string                          | StepsLabelPlacement                         |
| Steps                 | Type               | string                          | StepsType                                   |
| Steps                 | Size               | string                          | StepsSize                                   |
| Steps                 | Status             | string                          | StepsStatus                                 |
| ITableSortModel       | Sort               | string                          | Removed, see SortDirection                  |
| Column                | DefaultSortOrder   | SortDirection                   | SortDirection?                              |
| ColumnBase            | Fixed              | string                          | ColumnFixPlacement?                         |
| Selection             | Type               | string                          | SelectionType                               |
| Tag                   | Color              | string                          | OneOf<TagColor, string>                     |
| Tag                   | PresetColor        | PresetColor?                    | Removed, use Color                          |
| TimelineItem          | Color              | string                          | OneOf<TimelineDotColor, string>             |
| TypographyBase        | Type               | string                          | TextElementType?                            |
| Upload                | ListType           | string                          | UploadListType                              |
| Upload                | Method             | string                          | OneOf<HttpMethod, string>                   |
| UploadButton          | ListType           | string                          | UploadListType                              |
| UploadButton          | Method             | string                          | OneOf<HttpMethod, string>                   |

Any magic string usage for icons has been changed to use the `IconType` static const class.

Additionally, some named have been changed to keep consistent formatting:
- All `Twotone` names related to icons have been renamed to `TwoTone`
- `Input.OnkeyDown` -> `Input.OnKeyDown`
- `Input.OnkeyUp` -> `Input.OnKeyUp`

Changes are reflected in documentation and all tests are passing

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @pathartl , this is a very big refactoring. And please add the `[PublicApi("1.1.0")]` attribute for all new parameters.

**Comment by pathartl** [comment]
I added `[Obsolete]` to the parameters that are no longer in use, however there were no parameter additions across all components. The changes implemented only affect the type of the parameter.

**Comment by ElderJames** [comment]
There are an exception was thrown in Avatar component.
image

**Comment by pathartl** [comment]
Thanks for pointing out issues with docs:

- Some functionality such as AvatarSize or cascading FormSize -> InputSize was broken, now fixed
- Broken demos have been fixed
- Usage of properties in docs have been updated to use enums
- I took the time to also update some of the English documentation

All 2888 tests in the .NET 9 test group passed for me.

**Review by ElderJames — APPROVED** [review]

**Comment by pathartl** [comment]
For anyone who wants to see how to fix breaking changes, I just converted over my project to v1.1.0 and made the necessary updates:
https://github.com/LANCommander/LANCommander/commit/66c589c4689782e959c5379325728505c6c78fc1

It took about 45 minutes to convert over. All properties should have valid Intellisense now, so refer to that for actual acceptable values.

**Pull request merged**
