### PR TITLE
Add stop propogation

### PR DESCRIPTION
**Pull request by Hona**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

N/A

### 💡 Background and solution

Events propogating cause many UI refreshes, and general lag - especially in forms/modals

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by Hona** [comment]
Test please @ElderJames

**Comment by ElderJames** [comment]
Thanks @Hona ,I don't quite understand what problem this is solving?

**Comment by Hona** [comment]
When propagation is normal it will send the event to all parent components causing quite a bit of lag. See related #1283

**Comment by ElderJames** [comment]
What I don't understand is why only these two events were stopped?

**Comment by Hona** [comment]
OnChange runs alot: (when there is no debounce, it will happen on every key press, or every X ms depending on the value). On Blazor Server applications this is very visible

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
