### PR TITLE
fix(module:select): Select overlay resize & allow growing

### LINKED ISSUE #1169: Select ,can the width of the selection box be the same as the widest item?
I am working on the log query function, but the fully name of the logger is very long, and the Select must be set wide enough to display it completely.
can the width of the selection box be the same as the widest item?

### Additional context
image

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
1. Fixes #1169 
2. When overlay visible, window resize does not resize the overlay

### 💡 Background and solution
1. The width of the dropdown was taken using js (getBoundingClientRect). Without this, the dropdown assumes the width of the widest element. So I introduced 2 new parameters: 
   - `PopupContainerGrowToMatchWidestItem` addresses directly the issue
   - `PopupContainerMaxWidth` allows to put a cap over growing (defaults to auto, so no cap)
2. Due to width being set by getBoundingClientRect, the resizing of overlay does not really work. So `Select` will subscribe to exactly the same js resize event as `OverlayTrigger`. When fired, new width is calculated. There is a problem here however - during shrinking, most of the times, vertical scrollbar is appearing. It is messing with measurement - this causes that when scrollbar appears, the calculated width is shorter by the width of the scrollbar. If slow resize is applied, this is not a problem. I could not figure out how to exclude scroll bar...
(btw antDesign has the same overall bug - no resize on window resize)
select_resizeIssue

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  added `PopupContainerGrowToMatchWidestItem` & `PopupContainerMaxWidth`         |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by anddrzejb** [comment]
@ElderJames please wait with merge, apparently I forgot about AntD `dropdownMatchSelectWidth`...

**Review by ElderJames — DISMISSED** [review]

**Comment by ElderJames** [comment]
Ok

**Comment by anddrzejb** [comment]
@ElderJames A question: in AntD there is a single field `dropdownMatchSelectWidth` that either accepts:
- bool - `true` means default current action, `false` means the dropdown will grow to fit largest item
- string - expected width of the dropdown.

This I believe is a limiting choice. I think we should also have similar option to what I proposed here originally - max width of the dropdown. So to cover scenario when a consumer would like to allow the dropdown to grow but not more than certain length. If you are ok with that, I would add property `DropdownMaxWidth`.

**Comment by ElderJames** [comment]
Adding a property `DropdownMaxWidth` is OK.

**Comment by anddrzejb** [comment]
Took me some time, but I noticed several other issues which were addressed here:
1. It seems that antD changed the html design - I applied the same changes. These changes were anyway necessary so [responsive `maxTagCount`](https://ant.design/components/select/#components-select-demo-responsive) could be implemented.
2. Before `SelectContent` was mixing the mode logic of `default`/`multiple`/`tags`. It proved to be quite problematic in terms of maintaining. So I split that into `default` part and `multiple`/`tags`.
3. Backspace behaviour was aligned with antD (removes last characters and when there are no characters, last item is removed).
4. Rendering optimizations for `SelectContent` (certain styles where needlessly recalculated & set multiple times).
5. If `EnableSearch` is on, then always focus on the input.
6. In previous design long items where not overflowing correctly and no ellipsis was applied - this PR addresses that. 

I made this module for quick visual inspection of most of the visual settings combinations, maybe it will be useful:
```razor
@using System.Text
<AntDesign.Row Gutter="(24, 8)">
	<AntDesign.Col Span="24">
		<h2>Mode: Default</h2>
	</AntDesign.Col>
	@for(int i = 0; i <= _maxSettings; i++ )
	{
		Setting setting = (Setting)i;
		<AntDesign.Col Span="6" Style="margin-bottom:8px;">		
			@Placeholder(setting) @((int)setting)
			<Select Mode="default"
					DataSource="@_list"
					@bind-Value=_defaultModeSelectedValue[((int)setting)]
					Placeholder="@Placeholder(setting)"
					ValueName="@nameof(Person.Value)"
					LabelName="@nameof(Person.Name)"
					DisabledName="@nameof(Person.IsDisabled)"				
					PrefixIcon=@Prefix(setting)
					SuffixIcon=@Suffix(setting)
					EnableSearch=@Searchable(setting)					
					AllowClear=@AllowClear(setting)
					OnSelectedItemChanged="@((p) => OnSelectedItemChangedHandler(p, setting))">
			</Select>

		</AntDesign.Col>
	}
</AntDesign.Row>
<br/>
<br/>
<AntDesign.Row Gutter="(24, 8)">
	<AntDesign.Col Span="24">
		<h2>Mode: Multiple</h2>
	</AntDesign.Col>
	@for(int i = 0; i <= _maxSettings; i++ )
	{
		Setting setting = (Setting)i;
		<AntDesign.Col Span="6" Style="margin-bottom:8px;">		
			@Placeholder(setting) @((int)setting)
			<Select Mode="multiple"
					DataSource="@_list"
					@bind-Values=_multipleModeSelectedValues[((int)setting)]
					Placeholder="@Placeholder(setting)"
					ValueName="@nameof(Person.Value)"
					LabelName="@nameof(Person.Name)"
					DisabledName="@nameof(Person.IsDisabled)"				
					PrefixIcon=@Prefix(setting)
					SuffixIcon=@Suffix(setting)
					EnableSearch=@Searchable(setting)					
					AllowClear=@AllowClear(setting)
					OnSelectedItemsChanged="@((p) => OnSelectedItemsChangedHandler(p, setting))">
			</Select>

		</AntDesign.Col>
	}
</AntDesign.Row>
<br/>
<br/>
<AntDesign.Row Gutter="(24, 8)">
	<AntDesign.Col Span="24">
		<h2>Mode: Tags</h2>
	</AntDesign.Col>
	@for(int i = 0; i <= _maxSettingsTags; i++ )
	{
		Setting setting = (Setting)i;
		<AntDesign.Col Span="6" Style="margin-bottom:8px;">		
			@Placeholder(setting) @((int)setting)
			<Select Mode="tags"
					DataSource="@_list"
					@bind-Values=_tagsModeSelectedValues[((int)setting)]
					Placeholder="@Placeholder(setting)"
					ValueName="@nameof(Person.Value)"
					LabelName="@nameof(Person.Name)"
					DisabledName="@nameof(Person.IsDisabled)"				
					PrefixIcon=@Prefix(setting)
					SuffixIcon=@Suffix(setting)
					EnableSearch=@Searchable(setting)					
					AllowClear=@AllowClear(setting)
					TokenSeparators="new [] {','}"
					OnSelectedItemsChanged="@((p) => OnSelectedItemsChangedHandler(p, setting))">
			</Select>

		</AntDesign.Col>
	}
</AntDesign.Row>

@code
{
	[Flags]
	enum Setting {
		None = 0,
		Prefix = 1 << 0,
		Suffix = 1 << 1, 
		AllowClear = 1 << 2,
		ItemDoesNotFit = 1 << 3, //item will not fit in SelectContent, ellipsis expected
		Searchable = 1 << 4, //not needed for tags
	}

	int _maxSettings = 0;
	int _maxSettingsTags = 0;
	string[] _defaultModeSelectedValue;
	IEnumerable<string>[] _multipleModeSelectedValues;
	IEnumerable<string>[] _tagsModeSelectedValues;

	RenderFragment sample = 
	@<Icon Type="setting"></Icon>
	;

	string Placeholder(Setting setting) 
	{
		var values = (Setting[])Enum.GetValues(typeof(Setting));
		if ((int)setting == 0)
			return Setting.None.ToString();
		return string.Join("-", values.Where(v => v != Setting.None && setting.HasFlag(v)).ToArray());
	}

	RenderFragment? Prefix(Setting setting) => setting.HasFlag(Setting.Prefix) ? sample : null;
	RenderFragment? Suffix(Setting setting) => setting.HasFlag(Setting.Suffix) ? sample : null;
	bool Searchable(Setting setting) => setting.HasFlag(Setting.Searchable);	
	bool AllowClear(Setting setting) => setting.HasFlag(Setting.AllowClear);	
	


	List<Person> _list;
	class Person
	{
		public string Value { get; set; }
		public string Name { get; set; }
		public bool IsDisabled { get; set; }
	}

    protected override void OnInitialized()
    {
		_maxSettings = ((Setting[])Enum.GetValues<Setting>()).Sum(v => (int)v);		
		_maxSettingsTags = ((Setting[])Enum.GetValues<Setting>()).Where(v => v != Setting.Searchable).Sum(v => (int)v);
        _list = new List<Person>
        {
            new Person {Value = "jack", Name = "Jack"},
            new Person {Value = "lucy", Name = "Lucy"},
            new Person {Value = "disabled", Name = "Disabled", IsDisabled = true},
            new Person {Value = "yaoming", Name = "YaoMing"},
            new Person {Value = "longName", Name = "Super long name that should not fit in the col6 length of select content"}
		};
		_defaultModeSelectedValue = new string[_maxSettings+1];
		_multipleModeSelectedValues = new List<string>[_maxSettings+1];
		_tagsModeSelectedValues = new List<string>[_maxSettingsTags+1];
		for(int i = 0; i <= _maxSettings; i++)
		{
			if (((Setting)i).HasFlag(Setting.ItemDoesNotFit))
			{			
				_defaultModeSelectedValue[i] = "longName";
				_multipleModeSelectedValues[i] = new List<string> { "longName" };
			}
			else 
			{
				_defaultModeSelectedValue[i] = "lucy";
				_multipleModeSelectedValues[i] = new List<string> { "lucy" };
			}
		}
		for(int i = 0; i <= _maxSettingsTags; i++)
		{
			if (((Setting)i).HasFlag(Setting.ItemDoesNotFit))
				_tagsModeSelectedValues[i] = new List<string> { "longName" };
			else 
				_tagsModeSelectedValues[i] = new List<string> { "lucy" };
		}
    }

    private void OnSelectedItemChangedHandler(Person value, Setting setting)
    {
		Console.WriteLine($"({Placeholder(setting)}) Selected: ${value?.Name}");
		StateHasChanged();
    }

    private void OnSelectedItemsChangedHandler(IEnumerable<Person> values, Setting setting)
    {
		var names = values?.Select(p => p.Name)?.ToArray() ?? new string[] { "<empty>"} ;
		Console.WriteLine($"({Placeholder(setting)}) Selected: ${string.Join(", ", names)}");
		StateHasChanged();
    }

}
```

@ElderJames Unless you have any comments, I think this can be merged now.

**Review by ElderJames — APPROVED** [review]
Thanks for the hard work.

**Pull request merged**
