### PR TITLE
Select enter on form

### LINKED ISSUE #1176: Select Component Problem (Modal Form)
### Describe the bug

Form submission is triggered when pressing **enter** key to select item in **Select** component.
(Pre-condition: Only **one** Select form item inside the modal form)

select

### Steps to reproduce (please include code)

```
<Modal @ref="ModalRef"
       Title="@Title"
       Visible="Visible"
       Draggable="true"
       OkText="@OkText"
       OnOk="OkButtonOnClick"
       OnCancel="CancelButtonOnClick">

    <Form @ref="FormRef"
          Model="@SampleData"
          ValidateOnChange="true"
          OnFinish="OnFinish"
          OnFinishFailed="OnFinishFailed"
          LabelColSpan="8"
          WrapperColSpan="16">

        <FormItem Label="Name">
            <Select DataSource="@_persons"
                    @bind-Value="@context.Name"
                    LabelName="@nameof(Person.Name)"
                    ValueName="@nameof(Person.Value)"
                    Placeholder="Select a person"
                    DefaultActiveFirstItem="false"
                    EnableSearch>
            </Select>
        </FormItem>
    </Form>
</Modal>

private void OkButtonOnClick(MouseEventArgs e)
{
	FormRef.Submit();
}
```

### Further technical details
- AntDesign Nuget Package 0.6.0

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
Fixes #1176 

### 💡 Background and solution
Except fixes to #1176, this commit also adds the following:
1. Clear selection when "Delete" key or "Backspace" key pressed.
2. Exposes new attribute `DisableSubmitFormOnEnter`: Default behavior for `Select` component on a `Form` is to submit on Enter. The exception is when Enter is pressed while select options are visible (then Enter will set picked option as the value). If `DisableSubmitFormOnEnter = true` then Enter will not submit on a `Form`.
3. Interop gets a new event handler that prevents default for passed array of keys (more flexible)
4. EditContext is notified about a change in `Select` component (if `Form.ValidateOnChange == true`)

Also, I can create a docs sample for `DisableSubmitFormOnEnter` behaviour based on this gif:
seelct_keyBehavior

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  new attribute `DisableSubmitFormOnEnter'   |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
That's cool. I think we may not need this new property. As long as Enter is pressed when the select is focused, the form will not submit.

**Comment by anddrzejb** [comment]
Let us get this straight - not when select is focused, but when select is focused and has overlay visible. When select is focused and no overlay is visible, then enter should submit the form.

**Comment by ElderJames** [comment]
Yes, when overlay is closed, the select exits the edit state. Then enter should submit the form.

**Comment by anddrzejb** [comment]
@ElderJames per request, the added functionality was removed in 6c5f8bc.

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
