### PR TITLE
fix:(module: locale): wrong day order

### PR DESCRIPTION
**Pull request by ocoka**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Localization

### 💡 Background and solution

incorrect day order displayed on calendars and datepickers for russian locale, relates to changes made in commit: 894439adec248573a9e19a20453a730307824e5c

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  fix day order in calendar header for russian locale        |
| 🇨🇳 Chinese |           |

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @ocoka , could you please tell me if the first Day Of Week in Russian is Monday?

**Comment by ocoka** [comment]
> Thanks for contribution @ocoka , could you please tell me if the first Day Of Week in Russian is Monday?

Hello, yes it is

**Comment by ElderJames** [comment]
Hey @Alexbits , do we need to fix `ShortWeekDays` for all locale files if the `FirstDayOfWeek` is not Sunday?

It seems that we need a document to explain the structure of locales, and to look for people of the corresponding culture to supplement it.

**Comment by Alexbits** [comment]
> Hey @Alexbits , do we need to fix `ShortWeekDays` for all locale files if the `FirstDayOfWeek` is not Sunday?
@ElderJames Yes, the "shortWeekDays" should start with "Sunday" in the current implementation. I believe this can be improved with the use of System.Globalization as you say. I don't care about russian language though. I'm under russian rockets every day, they kill and rob people in Ukraine.

**Comment by ElderJames** [comment]
@Alexbits  Yes, we do oppose war, but not culture.

**Comment by ElderJames** [comment]
@Alexbits  Wish you peace.

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
