### PR TITLE
feat(module: button) add multithreaded wasm compatibility on .NET 8 R…

### PR DESCRIPTION
**Pull request by petertorocsik**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

I modified the Button's OnMouseUp event handler to use multithreaded mode in webassembly on .NET 8 RC1 platform to avoid error about instructs to use a dedicated worker for JS interop.

Without the modification, the following error occurs:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Please use dedicated worker for working with JavaScript interop. See https://aka.ms/dotnet-JS-interop-threads
System.InvalidOperationException: Please use dedicated worker for working with JavaScript interop. See https://aka.ms/dotnet-JS-interop-threads
   at System.Runtime.InteropServices.JavaScript.JSSynchronizationContext.AssertWebWorkerContext()
   at System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindJSFunctionImpl(String functionName, String moduleName, ReadOnlySpan`1 signatures)
   at System.Runtime.InteropServices.JavaScript.JSFunctionBinding.BindJSFunction(String functionName, String moduleName, ReadOnlySpan`1 signatures)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.ConsoleLoggerInterop.DotNetCriticalError(String message)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyConsoleLogger`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteMessage(LogLevel logLevel, String logName, Int32 eventId, String message, Exception exception)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyConsoleLogger`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Log[LogValues`1](LogLevel logLevel, EventId eventId, LogValues`1 state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|14_0[LogValues`1](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, LogValues`1& state)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @petertorocsik , may I ask how to reproduce the issue?

**Comment by petertorocsik** [comment]
You're welcome!

You need to create a simple webassembly project on the .NET 8 RC1 platform. You only need to insert one line in the project file:

<WasmEnableThreads>true</WasmEnableThreads>

No need to place the links to AntDesign's static files (CSS, JS). The contents of the project file are the follows:

<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<WasmEnableThreads>true</WasmEnableThreads>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AntDesign" Version="0.15.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-rc.1.23421.29" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-rc.1.23421.29" PrivateAssets="all" />
	</ItemGroup>

</Project>

Put a default AntDesign button:

<AntDesign.Button>Test</AntDesign.Button>

Click the button than the error message mentioned appears.

**Comment by ElderJames** [comment]
@petertorocsik That's all right. I think this issue would also appear in other components, right?

**Comment by petertorocsik** [comment]
@ElderJames Since there are complex components that use the Button, so these cases the error occurs for sure if any button is clicked.
The affected components are:

- AutoComplete
- DatePicker
- DropDown
- Modal
- Popconfirm
- Table
- Transfer

I searched in the AntDesign project for "await Task.Run" expression and I didn't find anything else (without await I found this in AsyncLazy.cs and ConventionRouter.cs) but regardless it's possible that this problem may occur but I don't really know what term to I search for it.

**Review by ElderJames — APPROVED** [review]
LGTM.

**Pull request merged**
