### PR TITLE
fix(module:upload): Upload list update fix

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
The code below, when adding a new file, will throw `NullReferenceException`.
```razor
@inject MessageService _message

<Upload @attributes="attrs"
        OnSingleCompleted="OnSingleCompleted"
        OnCompleted="HandleFileListChange">
    <Button Icon="upload">
        <span>点击上传</span>
    </Button>
</Upload>
@code
{
    Upload upload;

    Dictionary<string, object> attrs = new Dictionary<string, object>
{
        {"Action", "https://www.mocky.io/v2/5cc8019d300000980a055e76" },
        {"Name", "files" },
        {"DefaultFileList", new List<UploadFileItem>
            {
                new UploadFileItem
                {
                    Id = "1",
                    FileName = "1.jpg",
                    Url = "https://www.baidu.com/1.jpg",
                    State = UploadState.Success
                }
            }
        }
    };

    void OnSingleCompleted(UploadInfo fileinfo)
    {
        if (fileinfo.File.State == UploadState.Success)
        {
            var result = fileinfo.File.GetResponse<ResponseModel>();
            fileinfo.File.Url = result.url;
        }
    }

    void HandleFileListChange(UploadInfo fileinfo)
    {
        Console.WriteLine($"HandleFileListChange: {fileinfo.File.FileName}, FileList count: {fileinfo.FileList.Count}");
    }

    public class ResponseModel
    {
        public string name { get; set; }

        public string status { get; set; }

        public string url { get; set; }

        public string thumbUrl { get; set; }
    }
}
```

### 💡 Background and solution
1. Bug fix (mentioned in Related Issue : the new file list was not assigned to local variable.
2. Typescript functions got type checked arguments for file upload.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
There's an unexpected icon here.
image

**Comment by anddrzejb** [comment]
That's curious. I did not really change any visuals...And looking at the docs, it is already there, so it must have been there before these changes. I will however check it and try to fix it in this PR. Even though I was silent for almost a month, I did some work and I have a number of pending PRs.

**Comment by ElderJames** [comment]
That's great!

**Comment by anddrzejb** [comment]
@ElderJames Have a look at commit 41c83f8.

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
