### PR TITLE
rewritten (module: select): Almost completely new - update 2

### PR DESCRIPTION
**Pull request by ElDiddi**
_GitKraken didn't want to open my repository anymore, after rebuilding the repository Github doesn't recognize the old PR or didn't want to append the PR to the existing one. Therefore a new PR._

!!! This PR is a Breaking Change !!!
Users who work with the select-module have to change their code after the merge.

Whats new?
- Datasource IEnumerable - @bind-Value and @bind-Values
- Typeparams TItemValue, TItem
- Two-Way binding for the modes default, multiple and tag.
- OnDataSourceChange event when the DataSource changes
- Decoupling the SelectOptions from the data model, maybe this would help for virtualization later. (virtualization is not implemented atm)
- Keyboard support (Arrow keys up/down, Home, End & Enter for selection)
- Sorting for groups and labels (None, Asc, Desc)
- Reflection for Value, Label, Disabled, GroupName
- EventCallback OnSelectedItemChanged and OnSelectedItemsChanged<IEnumerable>
- Optional search for all three modes
- CreateCustomTag Action, here the developer can add his own logic
- LabelTemplate & ItemTemplate simplified
- IgnoreItemChanges to improve performance through Reflection
- The demos and the API description are completely revised.

-- Update 2 --
- Simplification of the upgrade path ***
- Re-Added the property LabelInValue but it generates a functional Json string that you can parse with `Newtonsoft.Json` or `System.Text.Json`. It is only available when the SelectOption created without a DataStore. If you use the DataStore binding, you get the `TItem`.
- modified the CalendarHeader
- Prettified some demos
- Added the namespace AntDesign.Select.Internal for all classes which the user does not need.

*** Simplification
If you do not want to create the data binding using a DataSource, you can now use the ChildComponent `<SelectOptions></SelectOptions>` and create the `SelectOption` directly. This should avoid unnecessary source code which could be created by a DataSource binding. 
```
<Select @bind-Value="@_selectedValue"
        TItemValue="int"
        TItem="string">
	<SelectOptions>
                <SelectOption TItemValue="int" TItem="string" Value=1 Label="Jack" />
                <SelectOption TItemValue="int" TItem="string" Value=2 Label="Lucy" />
                <SelectOption TItemValue="int" TItem="string" Value=3 Label="Yaoming" Disabled />
                <SelectOption TItemValue="int" TItem="string" Value=4 Label="Frieda" />
	</SelectOptions>		
</Select>
```

** Note ***
Don't use a inline initialization of the Datastore. Like this:
```
<select DataSource="@(new List<MyClass> { new MyClass { Id=1, Name="Lucy" } })"
```

There is certainly still plenty of room for improvement.
The documentation for the demos needs to be translated into Chinese.

-- Update 4 --
- Added the old demos again to make the demos comparable to React/Angular.
- Changed some PropertyNames 
- Fixed a bug which triggered the OnSelectedItemsChanged event twice.

### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [x] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [x] Performance optimization
- [ ] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

PR affected the following issues:
DefaultValue of select works incorrect #235
Keyboard navigation #261
[select]Related select elements displaying issue #473
[select] Default value issue #508
[SELECT] form binding issue - can't reset #515
关于 select 的问题 #695 <-- should be fixed, worked for me
[Select] Please add TValue for value type conversion #724
bug(module: select): Custom tags cannot be created if a part of the tag lable is already in use #727
bug(module: select): Custom tags are not unchecked if they are cleared in the input field with the clear button #726
Unable to clear Select component's value #761

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElDiddi** [comment]
GitHub tease me, i haven't check in the `components/AntDesign.csproj`

**Comment by ElderJames** [comment]
You should rebase the master branch.

**Comment by Yuanxw612** [comment]
@ElDiddi 

After reading your writing method, I am a little confused about why TItemValue and TItem should be used at the same time, and SelectOption should also be used like this.I don't think it makes sense.You can do this entirely with a parameter, such as ValueType

Regarding the use of value types, I suggest
```
<Select @bind-Value="@_selectedValue" ValueType="int">
	<SelectOptions>
                <SelectOption Value=1 Label="Jack" />
                <SelectOption Value=2 Label="Lucy" />
                <SelectOption Value=3 Label="Yaoming" Disabled />
                <SelectOption Value=4 Label="Frieda" />
	</SelectOptions>		
</Select>
```

**Comment by ElDiddi** [comment]
Hey @Yuanxw612,

you have to specify the TItemValue and TItem explict for each SelectOption otherwise a compilation error will occur. I have not yet figured out how to pass TItemValue and TItem from the parent element to avoid the explicit naming. If I have tracked the iusses on github/aspnetcore correctly the typeparam cannot be derived at the moment. It was requested as a feature. 
I can not use TValue because one of the AntDesign Base classes converts the type of TValue to string. Which results in the fact that TValue would always be string and you can save yourself the hassle. (thats a internal AntDesign issue)
If you look at commercial 3rd party component manufacturers, there is no one who offers the flexibility to choose between the direct initialization of SelectOption and a binding via DataSource. On github/aspnetcore this feature for the Select component was requested about a year ago and has not yet been implemented.

**Comment by TimChen44** [comment]
@ElDiddi 
检查演示时发现一个问题。
A problem was found when checking the demo.

"自动分词"的Demo在复制带有”，“符号的文本后，组件并没有正确分词。
After copying the text with the symbol of "," in the Demo of "Automatic tokenization", the component did not segment correctly.

**Comment by ElderJames** [comment]
Hey @ElDiddi , has #695 been fixed?

**Comment by ElderJames** [comment]
@ElDiddi I think you may fixed #518 in this PR. Could you confirm?

**Comment by ElderJames** [comment]
In demo multiple selection, the display order of the selected items have to be the order of selection, not the order of options.

currently:
image


expected:
image

**Review by ElderJames — APPROVED** [review]
Merge this PR first and fix the rest through others.

**Pull request merged**
