### PR TITLE
Update SEO, fix surge

### PR DESCRIPTION
**Pull request by CAPCHIK**
### 🤔 This is a ...

- [x] New feature
- [x] Bug fix
- [x] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

1. GitHub pages for SPA with non-empty routes serve `404.html`, that file updated to include `<title>` and `<link rel="icon"`.
Share link examples

|VK.com|  WhatsApp | Facebook| 
|---|---|---|
| image | image | image

2. Surge.sh [uses fallback](https://surge.sh/help/adding-a-200-page-for-client-side-routing) named `200.html`, and for preview build workflow `404.html` can be copied to achieve the same behavior, as in GitHub Pages.

### 📝 Changelog
1. New title for non-empty routes in documentation
2. Support for non-empty routes in PR preview

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thank you. Dose it work?

**Comment by CAPCHIK** [comment]
https://preview-1925-antblazor.surge.sh/en-US/?p=/en-US/components/inputnumber works 

but old preview can't do this
https://preview-1923-antblazor.surge.sh/en-US/?p=/en-US/components/inputnumber

**Comment by CAPCHIK** [comment]
GitHub pages must works, because text `Single Page Apps for GitHub Pages` is not present in source code 

image

**Comment by ElderJames** [comment]
I want to use a [library](https://github.com/jsakamoto/BlazorWasmPreRendering.Build) to improve the SEO, but meet the issue about the router https://github.com/jsakamoto/BlazorWasmPreRendering.Build/issues/2

**Comment by ElderJames** [comment]
> https://preview-1925-antblazor.surge.sh/en-US/?p=/en-US/components/inputnumber works
> 
> but old preview can't do this
> https://preview-1923-antblazor.surge.sh/en-US/?p=/en-US/components/inputnumber

The page doesn't even open correctly in my case

**Comment by CAPCHIK** [comment]
> > https://preview-1925-antblazor.surge.sh/en-US/?p=/en-US/components/inputnumber works
> > but old preview can't do this
> > https://preview-1923-antblazor.surge.sh/en-US/?p=/en-US/components/inputnumber
> 
> The page doesn't even open correctly in my case

I want to try to repair referenced [library](https://github.com/jsakamoto/BlazorWasmPreRendering.Build) first. It looks very cool.

**Comment by ElderJames** [comment]
@CAPCHIK Yeah, that's great!

**Comment by ElderJames** [comment]
@CAPCHIK Any progress?

**Comment by CAPCHIK** [comment]
No, I did not start repairing the library for rendering

**Pull request closed without merging**
