### PR TITLE
fix(module: tag): Tag component style parameters are not rendered (#1846)

### PR DESCRIPTION
**Pull request by JohnHao421**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [x] Code style optimization
- [x] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/ant-design-blazor/ant-design-blazor/issues/1846

### 💡 Background and solution

Change the timing of calling `GetStyle`

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |      fix Tag component style parameters are not rendered     |
| 🇨🇳 Chinese |     修复Tag组件Style参数设置无效      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1847) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1847) before we can accept your contribution.<br/><br/>:x: JohnHao421 [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=1847)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=1847) it.</sub>

**Comment by JohnHao421** [comment]
One problem I overlooked was that this change would cause the Tag component not to rerender correctly when the Color parameter was changed externally

**Comment by ElderJames** [comment]
> One problem I overlooked was that this change would cause the Tag component not to rerender correctly when the Color parameter was changed externally

Maybe you can try to call `GetStyle` in `OnparameterSet()`;

**Comment by JohnHao421** [comment]
> > One problem I overlooked was that this change would cause the Tag component not to rerender correctly when the Color parameter was changed externally
> 
> Maybe you can try to call `GetStyle` in `OnParameterSet()`;

Yes, Good idea

**Review by ElderJames — APPROVED** [review]
LGTM

**Pull request merged**
