### PR TITLE
fix(module: datepicker): value not updated when changed programmatically

### PR DESCRIPTION
**Pull request by Alexbits**
### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link
https://github.com/ant-design-blazor/ant-design-blazor/issues/2538

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by Alexbits** [comment]
This PR should fix the issue with DataPicker. The RangePicker has the same problem, but it's more complex. I'm still working on fixing it.

**Comment by ElderJames** [comment]
Thanks @Alexbits , maybe this PR can be target to branch master.

**Comment by Alexbits** [comment]
> Thanks @Alexbits , maybe this PR can be target to branch master.

I wanted to commit `RangePicker` fixes here. But it's up to you of course. This fix also requires the previous changes from the `feature` branch.

**Comment by ElderJames** [comment]
That's fine. Just let it stay at feature.

**Comment by Alexbits** [comment]
> That's fine. Just let it stay at feature.

I believe this fixes RangePicker. It looks like I also found a bug when the left part (marked red on the screenshot) of the date selection panel always set the value to the picker with index 0, no matter that the 1 was active input 🤔.

image

**Comment by ElderJames** [comment]
> I believe this fixes RangePicker. It looks like I also found a bug when the left part (marked red on the screenshot) of the date selection panel always set the value to the picker with index 0, no matter that the 1 was active input 🤔.

Yes, I found this. I take it you haven't fixed the bug yet.

**Comment by Alexbits** [comment]
> > I believe this fixes RangePicker. It looks like I also found a bug when the left part (marked red on the screenshot) of the date selection panel always set the value to the picker with index 0, no matter that the 1 was active input 🤔.
> 
> Yes, I found this. I take it you haven't fixed the bug yet.

Hey @ElderJames I fixed it in the last commit.

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
