### PR TITLE
Add Parameter for Calling change on Input for InputNumber

### PR DESCRIPTION
**Pull request by rabberbock**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

I have a need to update as the user types. I added a Parameter to InputNumber that can be used to set whether OnCgange will be called on an input event.

Any thoughts on this behavior and approach?

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by rabberbock** [comment]
@ElderJames Just wanted to check in before actually implementing that you would open to this change. Thanks!

**Comment by ElderJames** [comment]
@rabberbock Thanks for contribute this. 
Actually, we have added this mechanism to Input, currently through delayed binding, to solve the problems caused by fast input.

What we need at the moment is to add a switch to disable modification-time binding, as the time delay causes the entry characters to be rolled back when using Server mode.

**Comment by rabberbock** [comment]
@ElderJames I see. Would this be a better implementation for now as it does not update the value right away, but allows the caller to supply an OnInput?

**Comment by rabberbock** [comment]
@ElderJames Would you be open to this change in a different PR?

**Pull request closed without merging**
