### PR TITLE
feat(module:table): bring PR1208 to PR1303 merge master into feature

### PR DESCRIPTION
**Pull request by anddrzejb**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (about what?)

### 🔗 Related issue link
PR #1303 caused code duplication with PR #1208. This fixes this issue.

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by ElderJames — APPROVED** [review]
I'm sorry. Thanks for finding that.

**Comment by anddrzejb** [comment]
I try to check my features at least (especially that my production code already depends on them). Shall I understand that code in feature branch will not be merged into master until we reach v1.0?

**Comment by ElderJames** [comment]
Nope. We will release 0.8.0 after merge feature into master later, in this weekend. 
Because we just release 0.7.4 today, so I update the feature branch.

**Comment by anddrzejb** [comment]
Oh, that's great. Thanks!

**Pull request merged**
