### PR TITLE
Feature/documentation automation

### PR DESCRIPTION
**Pull request by kooliokey**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [X] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#2832 

### 💡 Background and solution
Documentation for the site will now be automatically generated with a combination of XML documentation comments and data attributes put on library components. All comments are expected/assumed to be in English and translations are made to generate the Chinese documentation. We still retain the ability to specify the Chinese translation for summaries though in cases where the automatic translation may be invalid. 

Full details can be read in the new markdown file `DOCUMENTATION.md` in this PR.

There are also a handful of spots where things were never used that have been removed. It may be worth skimming through to generate a changelog at somepoint for those changes.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | Documentation is generated from the code files now so the site should match the library much closer. Removed a handful of public properties, methods, etc that should not have been public. Some never did anything and some were for internal component functionality. See full changelog for detailed list. |
| 🇨🇳 Chinese | 文档现在是从代码文件生成的，因此该站点应该更接近于库。删除了一些不应该公开的公共属性、方法等。有些什么都没做，有些是为了内部组件功能。有关详细列表，请参阅完整的更新日志。|

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [X] Doc is updated/provided or not needed
- [X] Demo is updated/provided or not needed
- [X] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Very cool @kooliokey , please rebase to release branch for this PR.

**Comment by kooliokey** [comment]
> Very cool @kooliokey , please rebase to release branch for this PR.

I rebased off `feature` and still have a bunch of changes that weren't mine. Perhaps `master` hasn't been merged into `feature` in a while?

**Comment by ElderJames** [comment]
Yes, we haven't merge the master to feature. You can skip the commit not yours during the rebase.

**Comment by ElderJames** [comment]
hello @kooliokey , google tanslate service is not available in China, so we may need to use bing.

**Comment by kooliokey** [comment]
> hello @kooliokey , google tanslate service is not available in China, so we may need to use bing.

Oh, I didn't realize that. I'll have to see if it is possible to use Bing this way. Ideally we need to replace this implementation with a real API. Are there any that Microsoft gives for being in the dot net foundation? Or maybe some service you can get since the project is open source?

**Comment by kooliokey** [comment]
@ElderJames We may be able to get away with using Azure Translator's API. It allows 2 million characters a month for free. The total characters currently translated are just under 95k so we could translate the entire documentation 21 times a month. I can set up an account for me to test with. Could a Github build translate in PRs and commit the change to the JSON file to the PR? I think that's the only way it would make sense for an API requiring credentials to be used. Individuals could always provide their own to run locally if desired.

Pricing https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/#pricing
image

**Comment by kooliokey** [comment]
> @ElderJames We may be able to get away with using Azure Translator's API. It allows 2 million characters a month for free. The total characters currently translated are just under 95k so we could translate the entire documentation 21 times a month. I can set up an account for me to test with. Could a Github build translate in PRs and commit the change to the JSON file to the PR? I think that's the only way it would make sense for an API requiring credentials to be used. Individuals could always provide their own to run locally if desired.
> 
> Pricing https://azure.microsoft.com/en-us/pricing/details/cognitive-services/translator/#pricing image

@ElderJames I went ahead and added an `AzureTranslate` service as the default one used, but left Google in there as an option as well if someone wants to switch. The Azure one will require a user to set up an account and provide a Key to use.

**Comment by ElderJames** [comment]
Thank you @kooliokey , I think we need to follback to English while the translate service is blocken.

**Comment by kooliokey** [comment]
> Thank you @kooliokey , I think we need to follback to English while the translate service is blocken.

Yeah, that makes sense. I went ahead and did that now. It also won't cache it so that when build is ran again it will still try to translate it since it wasn't able to the first time.

**Comment by ElderJames** [comment]
That's fine. I will continue to fix the building and merge.

**Comment by kooliokey** [comment]
@ElderJames Is there anything I can do to help get this merged?

**Comment by kooliokey** [comment]
@ElderJames Would this action help with committing the changes to the translations made in the PR? https://github.com/marketplace/actions/git-auto-commit 

Looks like it allows committing changes to the branch of the PR and lets you provide a glob pattern for selecting the file(s) to commit which would let us just target the translation cache file.

**Comment by ElderJames** [comment]
@kooliokey Thank you, I will rebase these commits to the feature branch.

**Comment by ElderJames** [comment]
I haven't success to build the site yet. 😂

**Comment by ElderJames** [comment]
@kooliokey We will merge this feature when we rewrite the documentation site for antd v5.

**Review by ElderJames — APPROVED** [review]
I'm merging this PR, thank you @kooliokey ! This is big help!

**Pull request merged**
