### PR TITLE
feat:add maui test app

### PR DESCRIPTION
**Pull request by charleypeng**
Add maui app example, yet with several page error remain to be fixed. However it just runs as an example

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=2842) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=2842) before we can accept your contribution.<br/><br/>:x: charleypeng [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=2842)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=2842) it.</sub>

**Comment by charleypeng** [comment]
i just pull the code, you can put wherever you want 😉

**Comment by ElderJames** [comment]
How about I create another repository and you push the code to it?

**Comment by charleypeng** [comment]
ok

**Comment by ElderJames** [comment]
@charleypeng https://github.com/ant-design-blazor/demo-maui

**Pull request closed without merging**
