### PR TITLE
feat(module: table): adding a new method to resolve table collapse while using table.Reload

### PR DESCRIPTION
**Pull request by Vik1ang**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#2815 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |    adding a new method to resolve table collapse while reload table       |
| 🇨🇳 Chinese |      添加了一个新方法解决因为table.Reload 导致原本展开的表格缩回去了     |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=2824) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=2824) before we can accept your contribution.<br/><br/>:x: Vik1ang [sign now](https://cla.dotnetfoundation.org/ant-design-blazor/ant-design-blazor?pullRequest=2824)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/ant-design-blazor/ant-design-blazor?pullRequest=2824) it.</sub>

**Comment by LeaFrock** [comment]
You're committing a new feature and you should fork the origin `feature` branch and make your code changes. 

But now you're merging your codes forked from original `master` into `feature`. It won't be accepted.

**Comment by ElderJames** [comment]
I don't think it makes sense to implement this functionality by adding parameters to a method. It is better to add a property to the component, or to implement it through other existing functionality.

**Comment by ElderJames** [comment]
I have fix the issue by another way https://github.com/ant-design-blazor/ant-design-blazor/pull/3785

**Pull request closed without merging**
