### PR TITLE
feat(model: overlay): add boundary detection adjustment

### PR DESCRIPTION
**Pull request by mutouzdl**
### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

#1081 

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add overlay boundary detection and orientation adjustment      |
| 🇨🇳 Chinese |     增加overlay的边界检测和方向调整      |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by ElderJames — APPROVED** [review]
LGTM

**Comment by anddrzejb** [comment]
@mutouzdl Sorry to bother you about this, but I am trying to work out the overlay boundary calculation. I cannot figure out what is the meaning of `TriggerBoundaryAdjustMode.InScroll`. Do you remember what was that? I think I possibly am able to simplify the calculations, but I cannot figure out what that enum value really stands for (or how different calculations should be). I cannot find it used anywhere...

**Comment by mutouzdl** [comment]
@anddrzejb It's a little hard to understand, and I'll probably give you two examples to illustrate it.

Example1: In InScroll mode, in this case, the menu will appear on top.
This is because the browser is not high enough to fully display the menu below (even if the scroll bar is scrolled)
image


Example2: In InScroll mode, the following situation will display the menu below.
Although the browser height still doesn't seem to display the full menu, if you scroll the scroll bar, it will, so in this case, the menu will still expand below
image

If anything is unclear, I will try to explain further.

**Comment by anddrzejb** [comment]
@mutouzdl Thanks for the explanation! I think I understand now. So, we have these scenarios for calculations:
- `TriggerBoundaryAdjustMode.InView` - the default, the viewport boundaries are the boundaries we use for calculation. We try to fit the overlay so it is always fully visible in the viewport
- `TriggerBoundaryAdjustMode.InScroll` - the document boundaries are the boundaries used for calculation. So even if the overlay is outside of the viewport, the overlay may still be shown as long as it does not "overflow" the document boundaries.

**Comment by mutouzdl** [comment]
@anddrzejb Yes, your interpretation is correct, and your summary is very accurate!

**Comment by anddrzejb** [comment]
I will add this or similar explanation to the docs once I finish.

**Comment by anddrzejb** [comment]
@mutouzdl I have another question. I am trying to wrap my head around parameter `ArrowPointAtCenter`. What I can see here, this seems to me that it is doing exactly the same job as when setting one of the placements to the center placements (`Left`, `Right`, `Bottom`/`BottomCenter` or `Top`/`TopCenter`). Do I understand this correctly, or there is some more to this parameter that I am missing?

**Comment by anddrzejb** [comment]
@mutouzdl  I thought so. I was a bit confused by the calculation based on the arrow shifts. But the redesign will just switch internally to appropriate cantered placement I guess.

**Pull request merged**
