### PR TITLE
fix(module: tree): preventdefault for oncontextmenu

### PR DESCRIPTION
**Pull request by AndrewKaninchen**
…nContextMenuPreventDefaultRoot

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Site / documentation update
- [x] Demo update
- [ ] Component style update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 💡 Background and solution

Fixes the problem described by [lxarthea](https://github.com/lxatrhea) in
https://github.com/ant-design-blazor/ant-design-blazor/issues/1174#issuecomment-1415710619

Added two new parameters to the Tree component, OnContextMenuPreventDefault and OnContextMenuPreventDefaultRoot, which are used to determine whether the Tree (or its nodes) should prevent the default context menu or not.

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by ElderJames** [comment]
Thanks for contribution @AndrewKaninchen , but I prefer use a dictionary to setup conditional attribute to the html element.

**Comment by AndrewKaninchen** [comment]
> Thanks for contribution @AndrewKaninchen , but I prefer use a dictionary to setup conditional attribute to the html element.

Where can I see an example of this?

**Comment by AndrewKaninchen** [comment]
@ElderJames could you provide an example I can follow? I don't think I understood exactly what you meant

**Review by ElderJames — COMMENTED** [review]
LGTM

**Review by ElderJames — APPROVED** [review]

**Pull request merged**
